from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace

from argus_skill.life.context_packet import (
    create_mission_context,
    record_engineer_handoff,
    record_reviewed_handoff,
)
from argus_skill.reviewer import _find_decision_in_messages


def test_context_packet_seals_engineer_and_reviewer_handoffs(tmp_path: Path) -> None:
    mission = create_mission_context(
        life_dir=tmp_path,
        mission_id="mission-1",
        stage="research",
        scope="bounded",
        objective="Screen one candidate on public tasks.",
        acceptance_check="research/screen.json reports a binding pass/fail",
        non_goals=["do not preregister", "do not run GPU inference"],
        context_refs=[{
            "kind": "artifact",
            "ref": "research/IDEA_CANDIDATES.md",
            "why": "candidate universe",
            "content_hash": "abc",
        }],
        plan_id="plan-1",
        plan_version=1,
        node_key="screen",
    )
    checkpoint = mission.parent / "CHECKPOINT.md"
    checkpoint.write_text("# Current State\n\nScreen complete.\n", encoding="utf-8")
    control = mission.parent / "round-0001-engineer-control.json"
    control.write_text(
        '{"review":"required","skill_action":"none","skill_name":""}',
        encoding="utf-8",
    )

    engineer = record_engineer_handoff(
        mission_context_path=mission,
        round_index=1,
        engineer_summary="Created the screen packet.",
        checkpoint_path=checkpoint,
        control_path=control,
        thread_id="fresh-engineer-session",
    )
    assert engineer is not None
    latest = json.loads((mission.parent / "latest.json").read_text())
    mission_payload = json.loads(mission.read_text())
    engineer_payload = json.loads(engineer.read_text())
    assert latest["kind"] == "handoff_ref"
    assert latest["handoff"]["path"] == str(engineer)
    assert latest["handoff"]["sha256"]
    assert latest["mission"]["path"] == str(mission)
    assert mission_payload["stage"] == "research"
    assert mission_payload["scope"] == "bounded"
    assert mission_payload["objective"] == "Screen one candidate on public tasks."
    assert mission_payload["acceptance_check"].endswith("binding pass/fail")
    assert mission_payload["non_goals"] == [
        "do not preregister",
        "do not run GPU inference",
    ]
    assert mission_payload["context_refs"][0]["ref"] == "research/IDEA_CANDIDATES.md"
    assert not {
        "stage", "scope", "objective", "acceptance_check", "non_goals", "context_refs"
    } & latest.keys()
    assert engineer_payload["checkpoint"]["sha256"]
    assert engineer_payload["control"]["path"] == str(control)
    assert engineer_payload["control"]["sha256"]
    assert "text" not in engineer_payload["checkpoint"]
    assert "engineer_summary" not in engineer_payload

    reviewed = record_reviewed_handoff(
        mission_context_path=mission,
        round_index=1,
        engineer_summary="Created the screen packet.",
        review=SimpleNamespace(
            status="done",
            reason="Artifact verified.",
            next_action="Planner may choose the next frontier.",
            progress_class="decision",
            failure_cause="",
            failure_layer="",
            planner_report={
                "forward_progress": True,
                "plan_signal": "continue",
                "evidence_files": [{"path": "research/screen.json"}],
                "recommended_next": "legacy duplicate",
            },
            harness_control={"stage_reconciliation_required": True},
            checklist=[{
                "item": "solve.checkable-evidence",
                "satisfied": True,
                "evidence": "evidence regenerated byte-for-byte",
            }],
            certification_payload={
                "status": "done",
                "certified_claim_id": "C15/RUN-5",
                "exact_command_exit_zero": True,
                "byte_reproduction": True,
                "evidence_sha256": "960784a1e6c6d36d88307fdb10703852d4984640e672311bdef0dceea91f6a8e",
                "verifier_sha256": "e86260443b4e205ff44a27e15f12293c201aea8152c20dcf52b201f37af75426",
                "blockers": [],
                "checklist_counts": {"supported": 8, "not_applicable": 2},
                "checklist": {"solve.checkable-evidence": "PASS"},
            },
        ),
        checkpoint_path=checkpoint,
    )
    assert reviewed is not None
    latest = json.loads((mission.parent / "latest.json").read_text())
    reviewed_payload = json.loads(reviewed.read_text())
    assert latest["kind"] == "handoff_ref"
    assert latest["mission"] == {"path": str(mission)}
    assert latest["handoff"]["path"] == str(reviewed)
    assert reviewed_payload["review"]["status"] == "done"
    assert reviewed_payload["review"]["planner_report"]["plan_signal"] == "continue"
    assert "recommended_next" not in reviewed_payload["review"]["planner_report"]
    assert reviewed_payload["review"]["harness_control"] == {
        "stage_reconciliation_required": True
    }
    assert reviewed_payload["review"]["checklist"][0]["item"] == (
        "solve.checkable-evidence"
    )
    assert reviewed_payload["review"]["certification_payload"]["certified_claim_id"] == (
        "C15/RUN-5"
    )
    assert "engineer_summary" not in reviewed_payload
    assert "text" not in reviewed_payload["checkpoint"]


def test_framework_review_payload_projects_to_top_level_review(tmp_path: Path) -> None:
    mission = create_mission_context(
        life_dir=tmp_path,
        mission_id="mission-framework-review",
        stage="solve",
        scope="bounded",
        objective="Certify one bounded C21 packet.",
        acceptance_check="framework review object carries the bounded verdict",
    )
    checkpoint = mission.parent / "CHECKPOINT.md"
    checkpoint.write_text("# Current State\n\nReviewer certified C21.\n", encoding="utf-8")
    framework_payload = {
        "review": {
            "status": "done",
            "scope": "bounded",
            "correctness_status": "verified",
            "summary": "Bounded C21 certification is verified.",
            "checklist": [
                {
                    "checklist_id": "solve.checkable-evidence",
                    "verdict": "supported",
                    "evidence_refs": ["research/C21_SOLVE_REVIEWER_PACKET.json"],
                    "reviewer_notes": "Frozen packet is checkable.",
                }
            ],
            "blocking_issues": [],
        }
    }
    review = _find_decision_in_messages([json.dumps(framework_payload)])
    assert review is not None

    reviewed = record_reviewed_handoff(
        mission_context_path=mission,
        round_index=1,
        engineer_summary="Prepared C21 framework review repair.",
        review=review,
        checkpoint_path=checkpoint,
    )

    assert reviewed is not None
    reviewed_payload = json.loads(reviewed.read_text())
    review_payload = reviewed_payload["review"]
    assert review_payload["status"] == "done"
    assert review_payload["scope"] == "bounded"
    assert review_payload["correctness_status"] == "verified"
    assert review_payload["blocking_issues"] == []
    assert review_payload["checklist"] == framework_payload["review"]["checklist"]
    assert review_payload["certification_payload"] == framework_payload
