/** Dependency-free so legacy Python release commands can invoke Node directly. */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

interface Schema {
  const?: unknown;
  enum?: unknown[];
  type?: string | string[];
  properties?: Record<string, Schema>;
  required?: string[];
  items?: Schema;
  version?: number;
}

const root = new URL('../../../', import.meta.url);
const readJson = (path: string): unknown => JSON.parse(readFileSync(new URL(path, root), 'utf8'));
const payload = readJson('packages/contracts/schemas/event_payload_schemas.json') as {
  schema_version: number; events: Record<string, Schema>;
};
const api = readJson('packages/contracts/schemas/api_protocol.json') as {
  API_SERVICE: string; API_PROTOCOL_NAME: string; API_PROTOCOL_MAJOR: number;
  API_PROTOCOL_MINOR: number; SNAPSHOT_SCHEMA_VERSION: number; API_CAPABILITIES: string[];
};

function tsType(schema: Schema): string {
  if (Object.hasOwn(schema, 'const')) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map(value => JSON.stringify(value)).join(' | ');
  if (Array.isArray(schema.type)) return schema.type.map(type => tsType({ ...schema, type })).join(' | ');
  switch (schema.type) {
    case 'string': case 'boolean': case 'null': return schema.type;
    case 'integer': case 'number': return 'number';
    case 'array': return `Array<${tsType(schema.items ?? {})}>`;
    case 'object': {
      const fields = Object.entries(schema.properties ?? {});
      if (!fields.length) return 'Record<string, unknown>';
      return `{ ${fields.map(([key, value]) => `${JSON.stringify(key)}${schema.required?.includes(key) ? '' : '?'}: ${tsType(value)};`).join(' ')} }`;
    }
    default: return 'unknown';
  }
}

const header = '// Generated by packages/contracts/scripts/generate.ts. Do not edit.';
function eventTypes(): string {
  const lines = [header, "import type { EventMsg } from './events.js';", '',
    `export const EVENT_PAYLOAD_SCHEMA_VERSION = ${payload.schema_version};`, ''];
  const names = new Map<string, string>();
  for (const [type, schema] of Object.entries(payload.events)) {
    const name = type.split(/[._-]+/).map(part => part[0]?.toUpperCase() + part.slice(1)).join('') + 'Event';
    if ([...names.values()].includes(name)) throw new Error(`duplicate event interface ${name}`);
    names.set(type, name);
    lines.push(`export interface ${name} extends EventMsg {`, `  type: ${JSON.stringify(type)};`,
      `  payload_schema_version?: ${schema.version || 1};`);
    for (const [field, value] of Object.entries(schema.properties ?? {})) {
      lines.push(`  ${JSON.stringify(field)}${schema.required?.includes(field) ? '' : '?'}: ${tsType(value)};`);
    }
    lines.push('}', '');
  }
  lines.push('export interface EventPayloadByType {');
  for (const [type, name] of names) lines.push(`  ${JSON.stringify(type)}: ${name};`);
  lines.push('}', '', 'export type TypedArgusEvent = EventPayloadByType[keyof EventPayloadByType];', '');
  return lines.join('\n');
}

const artifacts = new Map<string, string>([
  ['packages/contracts/src/eventPayloads.generated.ts', eventTypes()],
  ['frontend/core/src/eventPayloads.generated.ts',
    `${header}\nexport * from '../../../packages/contracts/src/eventPayloads.generated.js';\n`],
  ['packages/contracts/src/apiProtocol.generated.ts', `${header}
export const API_SERVICE = ${JSON.stringify(api.API_SERVICE)};
export const API_PROTOCOL = { name: ${JSON.stringify(api.API_PROTOCOL_NAME)}, major: ${api.API_PROTOCOL_MAJOR}, minServerMinor: ${api.API_PROTOCOL_MINOR} } as const;
export const SNAPSHOT_SCHEMA_VERSION = ${api.SNAPSHOT_SCHEMA_VERSION};
export const REQUIRED_API_CAPABILITIES = ${JSON.stringify(api.API_CAPABILITIES, null, 2)} as const;
`],
]);

const args = process.argv.slice(2);
if (args.length === 2 && args[0] === '--render' && args[1] === 'event-types') {
  process.stdout.write(eventTypes());
} else if (args.length === 0 || (args.length === 1 && args[0] === '--check')) {
  for (const [path, content] of artifacts) {
    const url = new URL(path, root);
    if (args[0] === '--check') {
      let current = '';
      try { current = readFileSync(url, 'utf8'); } catch { /* Missing is stale. */ }
      if (current !== content) {
        process.stderr.write(`Stale contract: ${path}; run npm run contracts:generate\n`);
        process.exitCode = 1;
      }
    } else {
      writeFileSync(fileURLToPath(url), content, 'utf8');
    }
  }
} else {
  throw new Error('usage: generate.ts [--check | --render event-types]');
}
