"""Shared supervisor scope constants."""

PLANNER_SCOPE_BOUNDED = "bounded"
PLANNER_SCOPE_FINAL_SUBMISSION = "final_submission"
IDLE_BACKOFF_BASE_SECONDS = 15.0
IDLE_BACKOFF_CAP_SECONDS = 300.0
PLANNER_IDLE_JOURNAL_HEARTBEAT_SECONDS = 1800.0
PLAN_TERMINAL_IDLE = "planner_terminal_idle"

__all__ = [
    "IDLE_BACKOFF_BASE_SECONDS",
    "IDLE_BACKOFF_CAP_SECONDS",
    "PLANNER_IDLE_JOURNAL_HEARTBEAT_SECONDS",
    "PLANNER_SCOPE_BOUNDED",
    "PLANNER_SCOPE_FINAL_SUBMISSION",
    "PLAN_TERMINAL_IDLE",
]
