// Generated by argus_skill.release_tools.generate_event_fixtures. Do not edit.
import corpus from '../fixtures/eventCorpus.generated.json' with { type: 'json' };
import type { EventPayloadByType, TypedArgusEvent } from './eventPayloads.generated.js';

export type EventCorpusFixture = {
  [Type in keyof EventPayloadByType]: {
    readonly id: string;
    readonly event: EventPayloadByType[Type];
  };
}[keyof EventPayloadByType];

export interface EventCorpus {
  readonly schema_version: 1;
  readonly event_payload_schema_version: number;
  readonly fixtures: ReadonlyArray<EventCorpusFixture>;
}

export const EVENT_CORPUS = corpus as unknown as EventCorpus;
export type CorpusEvent = TypedArgusEvent;
