/** Canonical event names shared by the Web and terminal frontends. */
export const EVENT_TYPES = {
  AGENT_IO_START: 'agent.io.start',
  AGENT_IO_STREAM: 'agent.io.stream',
  AGENT_IO_COMPLETE: 'agent.io.complete',
  AGENT_IO_ERROR: 'agent.io.error',
  USAGE_RECORDED: 'usage.recorded',
  PROVIDER_REQUEST_STARTED: 'provider.request.started',
  PROVIDER_REQUEST_COMPLETED: 'provider.request.completed',
  PROVIDER_REQUEST_DENIED: 'provider.request.denied',
  CODEX_UTIL_COMPLETED: 'codex.util.completed',
  SKILL_COST_COMPLETED: 'skill.cost.completed',
  LOOP_START: 'loop.start',
  LOOP_DONE: 'loop.done',
  ROUND_START: 'round.start',
  ROUND_MAIN_COMPLETED: 'round.main.completed',
  ROUND_REVIEW_STARTED: 'round.review.started',
  ROUND_REVIEW_COMPLETED: 'round.review.completed',
  ROUND_ESCALATED: 'round.escalated',
  ROUND_STALL: 'round.stall',
  ROUND_REVIEWER_BACKEND_FAILURE: 'round.reviewer_backend_failure',
  ENGINEER_PROGRESS: 'engineer.progress',
  LIFE_STATUS: 'life.status',
  LIFE_PHASE_STARTED: 'life.phase.started',
  LIFE_MISSION_STARTED: 'life.mission.started',
  LIFE_MISSION_COMPLETED: 'life.mission.completed',
  LIFE_MISSION_FAILED: 'life.mission.failed',
  LIFE_MISSION_SKIPPED: 'life.mission.skipped',
  LIFE_MISSION_ORPHANED: 'life.mission.orphaned',
  LIFE_MISSION_REQUEUED: 'life.mission.requeued',
  LIFE_MANAGER_INTENT_STARTED: 'life.manager.intent.started',
  LIFE_MANAGER_INTENT_COMPLETED: 'life.manager.intent.completed',
  LIFE_MANAGER_INTENT_FAILED: 'life.manager.intent.failed',
  LIFE_MANAGER_STAGE_DECISION: 'life.manager.stage_decision',
  LIFE_VERTICAL_RESOLVED: 'life.vertical.resolved',
  LIFE_PLANNER_START: 'life.planner.start',
  LIFE_PLANNER_TASK_ADDED: 'life.planner.task_added',
  LIFE_PLANNER_TASK_SKIPPED: 'life.planner.task_skipped',
  LIFE_PLANNER_VERDICT: 'life.planner.verdict',
  LIFE_PLANNER_WAITING: 'life.planner.waiting',
  LIFE_PLANNER_TERMINAL_IDLE: 'life.planner.terminal_idle',
  LIFE_PLANNER_VERIFICATION_PROBE: 'life.planner.verification_probe',
  LIFE_PLANNER_STALL_ESCALATION: 'life.planner.stall_escalation',
  LIFE_PLANNER_ERROR: 'life.planner.error',
  LIFE_BUDGET_PAUSE: 'life.budget.pause',
  LIFE_LIFECYCLE_BLOCK: 'life.lifecycle.block',
  LIFE_LIFECYCLE_TRANSITION: 'life.lifecycle.transition',
  LIFE_INBOX_QUEUED: 'life.inbox.queued',
  LIFE_DAEMON_IDLE_TIMEOUT: 'life.daemon.idle_timeout',
  DAEMON_PARKED: 'daemon.parked',
  IDEA_SEARCH_STARTED: 'idea.search.started',
  IDEA_SEARCH_COMPLETED: 'idea.search.completed',
  IDEA_SEARCH_SKIPPED: 'idea.search.skipped',
  SKILL_CREATED: 'skill.created',
  SKILL_UPDATED: 'skill.updated',
  SKILL_ARCHIVED: 'skill.archived',
  OPERATOR_ALERT: 'operator_alert',
} as const;

export type CatalogEventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];

export const LEGACY_EVENT_ALIASES: Readonly<Record<string, CatalogEventType>> = {
  'loop.started': EVENT_TYPES.LOOP_START,
  'loop.completed': EVENT_TYPES.LOOP_DONE,
  'round.started': EVENT_TYPES.ROUND_START,
  'mission.started': EVENT_TYPES.LIFE_MISSION_STARTED,
  'mission.completed': EVENT_TYPES.LIFE_MISSION_COMPLETED,
  'mission.error': EVENT_TYPES.LIFE_MISSION_FAILED,
};

export const SIGNAL_EVENT_TYPES = new Set<CatalogEventType>([
  EVENT_TYPES.LOOP_START,
  EVENT_TYPES.LOOP_DONE,
  EVENT_TYPES.ROUND_START,
  EVENT_TYPES.ROUND_MAIN_COMPLETED,
  EVENT_TYPES.ROUND_REVIEW_COMPLETED,
  EVENT_TYPES.ROUND_ESCALATED,
  EVENT_TYPES.ROUND_STALL,
  EVENT_TYPES.ROUND_REVIEWER_BACKEND_FAILURE,
  EVENT_TYPES.SKILL_CREATED,
  EVENT_TYPES.SKILL_UPDATED,
  EVENT_TYPES.SKILL_ARCHIVED,
  EVENT_TYPES.LIFE_MISSION_STARTED,
  EVENT_TYPES.LIFE_MISSION_COMPLETED,
  EVENT_TYPES.LIFE_MANAGER_INTENT_STARTED,
  EVENT_TYPES.LIFE_MANAGER_INTENT_COMPLETED,
  EVENT_TYPES.LIFE_MANAGER_INTENT_FAILED,
  EVENT_TYPES.LIFE_MANAGER_STAGE_DECISION,
  EVENT_TYPES.LIFE_VERTICAL_RESOLVED,
  EVENT_TYPES.LIFE_PLANNER_START,
  EVENT_TYPES.LIFE_PLANNER_TASK_ADDED,
  EVENT_TYPES.LIFE_PLANNER_TASK_SKIPPED,
  EVENT_TYPES.LIFE_PLANNER_VERDICT,
  EVENT_TYPES.LIFE_PLANNER_WAITING,
  EVENT_TYPES.LIFE_PLANNER_TERMINAL_IDLE,
  EVENT_TYPES.LIFE_PLANNER_VERIFICATION_PROBE,
  EVENT_TYPES.LIFE_PLANNER_STALL_ESCALATION,
  EVENT_TYPES.LIFE_BUDGET_PAUSE,
  EVENT_TYPES.LIFE_LIFECYCLE_BLOCK,
  EVENT_TYPES.LIFE_LIFECYCLE_TRANSITION,
  EVENT_TYPES.PROVIDER_REQUEST_STARTED,
  EVENT_TYPES.PROVIDER_REQUEST_COMPLETED,
  EVENT_TYPES.PROVIDER_REQUEST_DENIED,
  EVENT_TYPES.LIFE_INBOX_QUEUED,
  EVENT_TYPES.LIFE_DAEMON_IDLE_TIMEOUT,
  EVENT_TYPES.DAEMON_PARKED,
  EVENT_TYPES.IDEA_SEARCH_STARTED,
  EVENT_TYPES.IDEA_SEARCH_COMPLETED,
  EVENT_TYPES.IDEA_SEARCH_SKIPPED,
  EVENT_TYPES.OPERATOR_ALERT,
]);

export const CALL_SCOPED_EVENT_TYPES = new Set<CatalogEventType>([
  EVENT_TYPES.AGENT_IO_START,
  EVENT_TYPES.AGENT_IO_COMPLETE,
  EVENT_TYPES.AGENT_IO_ERROR,
  EVENT_TYPES.PROVIDER_REQUEST_STARTED,
  EVENT_TYPES.PROVIDER_REQUEST_COMPLETED,
  EVENT_TYPES.PROVIDER_REQUEST_DENIED,
  EVENT_TYPES.USAGE_RECORDED,
]);

export function canonicalEventType(value: unknown): string {
  const type = String(value ?? '').trim();
  return LEGACY_EVENT_ALIASES[type] ?? type;
}
