// Generated by argus_skill.release_tools.generate_event_types. Do not edit.
import type { EventMsg } from './types.js';

export const EVENT_PAYLOAD_SCHEMA_VERSION = 2;

export interface AgentIoStartEvent extends EventMsg {
  type: "agent.io.start";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label": string;
  "backend"?: string;
  "model"?: string | null;
  "working_dir"?: string | null;
  "resume_thread_id"?: string | null;
}

export interface AgentIoStreamEvent extends EventMsg {
  type: "agent.io.stream";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label"?: string | null;
  "stream": "stdout" | "stderr";
  "line": string;
}

export interface AgentIoCompleteEvent extends EventMsg {
  type: "agent.io.complete";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label": string;
  "backend"?: string;
  "model"?: string | null;
  "exit_code"?: number | null;
  "thread_id"?: string | null;
  "fatal_error"?: string | null;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "cache_write_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "premium_requests"?: number | null;
  "premium_requests_present"?: boolean;
  "total_nano_aiu"?: number | null;
}

export interface AgentIoErrorEvent extends EventMsg {
  type: "agent.io.error";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label"?: string;
  "backend"?: string;
  "error": string;
}

export interface UsageRecordedEvent extends EventMsg {
  type: "usage.recorded";
  payload_schema_version?: 2;
  "call_id": string;
  "schema_version": 2;
  "project_id"?: string;
  "mission_id"?: string | null;
  "thread_id"?: string | null;
  "provider": string;
  "model"?: string;
  "run_label"?: string;
  "status": "completed" | "error" | "denied";
  "duration_ms"?: number;
  "usage": Record<string, unknown>;
  "pricing": Record<string, unknown>;
}

export interface ProviderRequestStartedEvent extends EventMsg {
  type: "provider.request.started";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "daily_calls"?: number;
  "daily_cap"?: number;
}

export interface ProviderRequestCompletedEvent extends EventMsg {
  type: "provider.request.completed";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "success"?: boolean;
  "error"?: string;
  "premium_requests"?: number;
}

export interface ProviderRequestDeniedEvent extends EventMsg {
  type: "provider.request.denied";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "reason"?: string;
}

export interface BudgetReservationCreatedEvent extends EventMsg {
  type: "budget.reservation.created";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd": number;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface BudgetReservationDeniedEvent extends EventMsg {
  type: "budget.reservation.denied";
  payload_schema_version?: 1;
  "call_id": string;
  "reason": string;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface BudgetReservationSettledEvent extends EventMsg {
  type: "budget.reservation.settled";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd"?: number;
  "cost_usd"?: number | null;
  "overrun_usd"?: number | null;
  "pricing_status": string;
}

export interface BudgetReservationReleasedEvent extends EventMsg {
  type: "budget.reservation.released";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd"?: number;
  "reason"?: string;
}

export interface BudgetUnpricedBlockedEvent extends EventMsg {
  type: "budget.unpriced.blocked";
  payload_schema_version?: 1;
  "call_id": string;
  "reason": string;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface LifeMissionStartedEvent extends EventMsg {
  type: "life.mission.started";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
  "scope"?: string;
  "missions_started"?: number;
  "attempt"?: number;
  "usage_attempt_id"?: string;
}

export interface LifeMissionCompletedEvent extends EventMsg {
  type: "life.mission.completed";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
  "scope"?: string;
  "status": string;
  "summary"?: string;
  "outcome_class"?: "completed" | "incomplete" | "stalled" | "blocked" | "failed" | "ended";
  "outcome"?: { "execution_status": string; "review_status": string; "stage_certification": string; "interruption_kind": string; "resumable": boolean; };
  "success"?: boolean;
  "overall_complete"?: boolean;
  "campaign_continues"?: boolean;
  "execution_workdir"?: string;
  "delivery_candidates"?: Array<string>;
  "rounds"?: number;
  "elapsed_seconds"?: number;
  "cost_usd"?: number | null;
  "known_cost_usd"?: number;
  "pricing_status"?: string;
  "research_result"?: Record<string, unknown> | null;
  "repair_capability"?: Record<string, unknown> | null;
  "stop_kind"?: "budget_exhausted" | "provider_cooldown" | "provider_fence" | "daemon_shutdown" | "operator_pause" | "operator_abort" | "backend_unavailable" | "transient_error" | "permanent_error" | null;
  "recoverable"?: boolean;
  "delivery_id"?: string;
  "delivery"?: { "schema_version"?: number; "delivery_id"?: string; "kind"?: string; "item_id"?: string; "title"?: string; "summary"?: string; "status"?: string; "review_status"?: string; "delivered_at"?: number; "primary_target"?: Record<string, unknown> | null; "targets"?: Array<Record<string, unknown>>; } | null;
  "operator_question"?: string;
}

export interface RoundStartEvent extends EventMsg {
  type: "round.start";
  payload_schema_version?: 1;
  "round_index": number;
  "round_max"?: number;
  "session_id"?: string | null;
}

export interface RoundMainCompletedEvent extends EventMsg {
  type: "round.main.completed";
  payload_schema_version?: 1;
  "round_index": number;
  "exit_code"?: number;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "stop_kind"?: "budget_exhausted" | "provider_cooldown" | "provider_fence" | "daemon_shutdown" | "operator_pause" | "operator_abort" | "backend_unavailable" | "transient_error" | "permanent_error" | null;
}

export interface RoundReviewStartedEvent extends EventMsg {
  type: "round.review.started";
  payload_schema_version?: 1;
  "round_index": number;
  "status"?: string;
}

export interface RoundReviewDeferredEvent extends EventMsg {
  type: "round.review.deferred";
  payload_schema_version?: 1;
  "round_index": number;
  "round_max"?: number;
  "next_step": string;
  "deferral_count"?: number;
  "deferral_limit"?: number;
}

export interface RoundReviewCompletedEvent extends EventMsg {
  type: "round.review.completed";
  payload_schema_version?: 1;
  "round_index"?: number;
  "status": "done" | "continue" | "blocked" | "replan_requested" | "error" | "research_incomplete" | "paused_no_breakthrough" | "exhausted_current_methods";
  "reason": string;
  "next_action"?: string;
  "operator_question"?: string;
  "operator_options"?: Array<{ "id"?: string; "label"?: string; "description"?: string; "requires_note"?: boolean; }>;
  "review_source"?: string;
  "forward_progress"?: boolean;
  "plan_signal"?: string;
  "plan_challenge"?: string;
  "plan_alternative"?: string;
  "authority_impact"?: string;
  "frontier_change"?: string;
  "frontier_summary"?: string;
  "session_signal"?: Record<string, unknown>;
  "text"?: string;
  "review_skipped"?: boolean;
  "prompt_block_stats"?: Record<string, unknown>;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "premium_requests"?: number;
  "backend_unavailable"?: boolean;
  "usage_scope"?: "delta";
  "stop_kind"?: "budget_exhausted" | "provider_cooldown" | "provider_fence" | "daemon_shutdown" | "operator_pause" | "operator_abort" | "backend_unavailable" | "transient_error" | "permanent_error" | null;
}

export interface RoundSecretRedactedEvent extends EventMsg {
  type: "round.secret_redacted";
  payload_schema_version?: 1;
  "round_index": number;
  "round_max"?: number;
  "redacted_paths": Array<string>;
  "replacement_count": number;
  "scanned_files"?: number;
  "scan_errors"?: Array<string>;
  "truncated"?: boolean;
  "operator_alert"?: boolean;
}

export interface LifePlannerStartEvent extends EventMsg {
  type: "life.planner.start";
  payload_schema_version?: 1;
  "manager_intent"?: Record<string, unknown>;
  "cycle"?: number;
}

export interface LifePlannerVerdictEvent extends EventMsg {
  type: "life.planner.verdict";
  payload_schema_version?: 1;
  "status": "planned" | "completed" | "research_incomplete" | "paused_budget" | "paused_no_breakthrough" | "exhausted_current_methods" | "provider_cooldown" | "infra_blocked" | "error";
  "success": boolean;
  "recoverable": boolean;
  "reason": string;
  "summary": string;
  "project_id": string;
  "mission_id": string;
  "research_target_level"?: string | null;
  "correctness_status"?: string | null;
  "novelty_status"?: string | null;
  "significance_status"?: string | null;
  "stop_kind"?: string | null;
  "completion_kind"?: string | null;
  "delivery_id"?: string;
  "delivery"?: Record<string, unknown> | null;
  "tasks_added"?: number;
}

export interface LifePlannerErrorEvent extends EventMsg {
  type: "life.planner.error";
  payload_schema_version?: 1;
  "error": string;
  "reason"?: string;
}

export interface LifeRuntimeFailureCircuitOpenedEvent extends EventMsg {
  type: "life.runtime_failure.circuit_opened";
  payload_schema_version?: 1;
  "item_id"?: string;
  "fingerprint": string;
  "exception_type": string;
  "callsite": string;
  "normalized_error"?: string;
  "occurrence_count"?: number;
  "runtime_identity"?: Record<string, unknown>;
  "newly_opened"?: boolean;
  "operator_alert"?: boolean;
}

export interface LifeRuntimeFailureCircuitBlockedEvent extends EventMsg {
  type: "life.runtime_failure.circuit_blocked";
  payload_schema_version?: 1;
  "item_id"?: string;
  "fingerprint": string;
  "exception_type"?: string;
  "callsite"?: string;
  "normalized_error"?: string;
  "occurrence_count"?: number;
  "runtime_identity"?: Record<string, unknown>;
  "operator_alert"?: boolean;
  "reason": string;
}

export interface LifeRuntimeFailureCanaryPassedEvent extends EventMsg {
  type: "life.runtime_failure.canary_passed";
  payload_schema_version?: 1;
  "item_id": string;
  "circuit_cleared": boolean;
}

export interface LifePlannerTaskAddedEvent extends EventMsg {
  type: "life.planner.task_added";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
  "deps"?: Array<string>;
  "priority"?: number;
  "impact_score"?: number;
  "impact_area"?: string;
  "branch_id"?: string;
  "parent_branch_id"?: string | null;
}

export interface LifePlannerTaskSkippedEvent extends EventMsg {
  type: "life.planner.task_skipped";
  payload_schema_version?: 1;
  "item_id"?: string;
  "title"?: string;
  "reason": string;
}

export interface LifeManagerIntentCompletedEvent extends EventMsg {
  type: "life.manager.intent.completed";
  payload_schema_version?: 1;
  "intent_id": string;
  "item_id": string;
  "objective": string;
  "vertical": string;
  "kind": string;
  "stages": Array<string>;
  "route"?: string;
  "workflow_mode"?: string;
  "lifetime"?: string;
  "continuous"?: boolean;
  "open_ended"?: boolean;
  "reason"?: string;
}

export interface LifeManagerIntentFailedEvent extends EventMsg {
  type: "life.manager.intent.failed";
  payload_schema_version?: 1;
  "intent_id": string;
  "item_id"?: string | null;
  "objective": string;
  "error": string;
  "phase": "backend" | "parse" | "contract" | "timeout" | "unknown";
  "cause": string;
  "contract_field"?: string;
  "attempts": number;
  "model_reply_snippet"?: string;
  "backend_error"?: string;
  "answer_preserved"?: boolean;
}

export interface LifeManagerPlanChallengeDecidedEvent extends EventMsg {
  type: "life.manager.plan_challenge.decided";
  payload_schema_version?: 1;
  "item_id": string;
  "manager_action": "keep" | "revise" | "replace" | "ask_operator";
  "manager_reason"?: string;
  "challenge": string;
  "alternative"?: string;
  "authority_impact"?: string;
  "raised_at"?: number;
  "adjudicated_at": number;
  "revision_latency_seconds"?: number;
  "text"?: string;
}

export interface LifeInboxDrainedEvent extends EventMsg {
  type: "life.inbox.drained";
  payload_schema_version?: 1;
  "count": number;
  "messages": Array<string>;
}

export interface LifeOperatorQuestionPendingEvent extends EventMsg {
  type: "life.operator_question.pending";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "question": string;
  "agent_layer"?: string;
}

export interface LifeOperatorQuestionAnsweredEvent extends EventMsg {
  type: "life.operator_question.answered";
  payload_schema_version?: 1;
  "item_id": string;
  "continuation_item_id": string;
  "question": string;
  "manager_decision": string;
  "decision_id"?: string;
  "decision_revision"?: number | null;
  "campaign_generation"?: number | null;
  "stopped"?: boolean;
}

export interface RoleSessionTurnEvent extends EventMsg {
  type: "role.session.turn";
  payload_schema_version?: 1;
  "role": "planner" | "engineer" | "reviewer";
  "policy": "fresh" | "mission" | "rolling";
  "action": "fresh" | "resumed" | "rotated";
  "rotation_reason"?: string;
  "round_index"?: number;
  "planning_cycle"?: number;
  "session_id"?: string;
  "turns_on_session"?: number;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "duration_ms"?: number;
  "prompt_chars"?: number;
  "prompt_estimated_tokens"?: number;
  "capsule_path"?: string;
  "metadata_persisted"?: boolean;
  "persistence_warning"?: string;
  "signal_kind"?: "repeated_contradiction" | "reviewer_confusion" | "quality_degradation";
  "signal_detail"?: string;
}

export interface EngineerProgressEvent extends EventMsg {
  type: "engineer.progress";
  payload_schema_version?: 1;
  "kind": string;
  "text"?: string;
  "actor"?: string;
  "agent_layer"?: string;
  "message_id"?: string;
  "replace"?: boolean;
  "round_index"?: number;
  "experiment_id"?: string;
  "branch_id"?: string;
}

export interface SkillCreatedEvent extends EventMsg {
  type: "skill.created";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "name"?: string;
  "version"?: number;
  "scope"?: string;
  "path"?: string;
  "text"?: string;
}

export interface SkillUpdatedEvent extends EventMsg {
  type: "skill.updated";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "name"?: string;
  "version"?: number;
  "scope"?: string;
  "path"?: string;
  "text"?: string;
}

export interface SkillArchivedEvent extends EventMsg {
  type: "skill.archived";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "name"?: string;
  "version"?: number;
  "scope"?: string;
  "path"?: string;
  "reason"?: string;
  "text"?: string;
}

export interface SkillCostCompletedEvent extends EventMsg {
  type: "skill.cost.completed";
  payload_schema_version?: 1;
  "agent_layer"?: string;
  "matcher_model"?: string;
  "distiller_model"?: string;
  "matcher": Record<string, unknown>;
  "distiller": Record<string, unknown>;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "premium_requests"?: number;
  "usage_scope": "delta" | "cumulative";
}

export interface SkillTidiedEvent extends EventMsg {
  type: "skill.tidied";
  payload_schema_version?: 1;
  "name": string;
  "placement": "global" | "vertical";
  "vertical"?: string;
  "path": string;
  "text": string;
}

export interface SkillHistoryCompressedEvent extends EventMsg {
  type: "skill.history.compressed";
  payload_schema_version?: 1;
  "count": number;
  "keep_hot": number;
  "paths"?: Array<string>;
  "truncated"?: boolean;
  "bytes_before"?: number;
  "bytes_after"?: number;
  "bytes_saved"?: number;
  "text"?: string;
}

export interface SkillEvolutionCompletedEvent extends EventMsg {
  type: "skill.evolution.completed";
  payload_schema_version?: 1;
  "ops_proposed": number;
  "created": number;
  "updated": number;
  "archived": number;
  "rejected": number;
  "compaction_clusters"?: number;
  "compacted"?: number;
  "history_compressed"?: number;
  "history_bytes_saved"?: number;
  "errors"?: number;
  "project_skill_dir"?: string;
  "global_skill_dir"?: string;
  "project_skill_count"?: number;
  "global_skill_count"?: number;
  "text"?: string;
}

export interface WikiInitializedEvent extends EventMsg {
  type: "wiki.initialized";
  payload_schema_version?: 1;
  "project": string;
  "path": string;
  "auto": boolean;
  "text"?: string;
}

export interface WikiHookWarningEvent extends EventMsg {
  type: "wiki.hook.warning";
  payload_schema_version?: 1;
  "operation": string;
  "error": string;
  "text"?: string;
}

export interface WikiCreatedEvent extends EventMsg {
  type: "wiki.created";
  payload_schema_version?: 1;
  "page_id": string;
  "card_type": string;
  "title"?: string;
  "status"?: string;
  "path": string;
  "text"?: string;
}

export interface WikiUpdatedEvent extends EventMsg {
  type: "wiki.updated";
  payload_schema_version?: 1;
  "page_id": string;
  "card_type": string;
  "title"?: string;
  "status"?: string;
  "path": string;
  "text"?: string;
}

export interface WikiRetiredEvent extends EventMsg {
  type: "wiki.retired";
  payload_schema_version?: 1;
  "page_id": string;
  "card_type": string;
  "reason"?: string;
  "text"?: string;
}

export interface WikiPromotionPromotedEvent extends EventMsg {
  type: "wiki.promotion.promoted";
  payload_schema_version?: 1;
  "card_type": string;
  "page_id": string;
  "from_status": string;
  "to_status": string;
  "references"?: number;
  "successful_references"?: number;
  "failed_references"?: number;
  "text"?: string;
}

export interface WikiPromotionDemotedEvent extends EventMsg {
  type: "wiki.promotion.demoted";
  payload_schema_version?: 1;
  "card_type": string;
  "page_id": string;
  "from_status": string;
  "to_status": string;
  "references"?: number;
  "successful_references"?: number;
  "failed_references"?: number;
  "text"?: string;
}

export interface WikiRetiredCompressedEvent extends EventMsg {
  type: "wiki.retired.compressed";
  payload_schema_version?: 1;
  "count": number;
  "keep_hot": number;
  "paths"?: Array<string>;
  "truncated"?: boolean;
  "bytes_before"?: number;
  "bytes_after"?: number;
  "bytes_saved"?: number;
  "text"?: string;
}

export interface WikiEvolutionCompletedEvent extends EventMsg {
  type: "wiki.evolution.completed";
  payload_schema_version?: 1;
  "wiki_count": number;
  "ops_proposed"?: number;
  "sources"?: number;
  "scratch_pages"?: number;
  "created"?: number;
  "updated"?: number;
  "retired"?: number;
  "skipped"?: number;
  "rejected"?: number;
  "promoted"?: number;
  "demoted"?: number;
  "compaction_clusters"?: number;
  "compacted"?: number;
  "retired_compressed"?: number;
  "retired_bytes_saved"?: number;
  "errors"?: number;
  "paths"?: Array<string>;
  "text"?: string;
}

export interface ProjectCompletedEvent extends EventMsg {
  type: "project.completed";
  payload_schema_version?: 1;
  "vertical": string;
  "source": string;
  "required_gate": string;
  "evidence_refs": Array<string>;
  "from_state": string;
  "agent_layer"?: string;
}

export interface ProjectCompletionRefusedEvent extends EventMsg {
  type: "project.completion_refused";
  payload_schema_version?: 1;
  "vertical": string;
  "source": string;
  "required_gate": string;
  "reason": string;
  "agent_layer"?: string;
}

export interface ResearchAchievementCertifiedEvent extends EventMsg {
  type: "research.achievement.certified";
  payload_schema_version?: 1;
  "achievement_id": string;
  "title": string;
  "goal": string;
  "summary"?: string;
  "evidence"?: Array<string>;
  "reviewer_certified": true;
}

export interface DaemonCommandSubmittedEvent extends EventMsg {
  type: "daemon.command.submitted";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "revision": number;
  "expected_revision"?: number | null;
}

export interface DaemonCommandCompletedEvent extends EventMsg {
  type: "daemon.command.completed";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "status": "applied" | "failed";
  "revision": number;
  "error"?: string;
  "result"?: Record<string, unknown>;
}

export interface DaemonCommandRejectedEvent extends EventMsg {
  type: "daemon.command.rejected";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "status": "rejected";
  "revision": number;
  "error": string;
}

export interface LifeManagerBackendResolvedEvent extends EventMsg {
  type: "life.manager.backend_resolved";
  payload_schema_version?: 1;
  "role": string;
  "backend": string;
  "source": string;
}

export interface LifePlannerBackendResolvedEvent extends EventMsg {
  type: "life.planner.backend_resolved";
  payload_schema_version?: 1;
  "role": string;
  "backend": string;
  "source": string;
}

export interface LifeEngineerBackendResolvedEvent extends EventMsg {
  type: "life.engineer.backend_resolved";
  payload_schema_version?: 1;
  "role": string;
  "backend": string;
  "source": string;
}

export interface LifeReviewerBackendResolvedEvent extends EventMsg {
  type: "life.reviewer.backend_resolved";
  payload_schema_version?: 1;
  "role": string;
  "backend": string;
  "source": string;
}

export interface LifeCuratorBackendResolvedEvent extends EventMsg {
  type: "life.curator.backend_resolved";
  payload_schema_version?: 1;
  "role": string;
  "backend": string;
  "source": string;
}

export interface CodexUtilCompletedEvent extends EventMsg {
  type: "codex.util.completed";
  payload_schema_version?: 1;
  "agent_layer"?: string;
  "run_label"?: string;
  "model"?: string;
  "session_id"?: string;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "premium_requests"?: number;
  "usage_scope"?: string;
}

export interface LoopStartEvent extends EventMsg {
  type: "loop.start";
  payload_schema_version?: 1;
  "text"?: string;
  "objective"?: string;
  "max_rounds"?: number;
  "plan_mode"?: string;
}

export interface LoopDoneEvent extends EventMsg {
  type: "loop.done";
  payload_schema_version?: 1;
  "text"?: string;
  "success"?: boolean;
  "stop_reason"?: string;
}

export interface RoundCheckpointRecordedEvent extends EventMsg {
  type: "round.checkpoint.recorded";
  payload_schema_version?: 1;
  "round"?: number;
  "run_id"?: string;
  "ref"?: string;
}

export interface RoundCheckpointFailedEvent extends EventMsg {
  type: "round.checkpoint.failed";
  payload_schema_version?: 1;
  "round"?: number;
  "run_id"?: string;
  "error"?: string;
}

export interface RoundEscalatedEvent extends EventMsg {
  type: "round.escalated";
  payload_schema_version?: 1;
  "round_index"?: number;
  "soft_round_limit"?: number;
  "hard_escalate_rounds"?: number;
  "forward_progress"?: boolean;
  "continuation_reason"?: string;
  "text"?: string;
}

export interface RoundStallEvent extends EventMsg {
  type: "round.stall";
  payload_schema_version?: 1;
  "round_index"?: number;
  "round_max"?: number;
  "semantic_stall_streak"?: number;
  "stall_threshold"?: number;
  "decision_idle_seconds"?: number;
  "forward_progress"?: boolean;
  "text"?: string;
}

export interface RoundReviewerBackendFailureEvent extends EventMsg {
  type: "round.reviewer_backend_failure";
  payload_schema_version?: 1;
  "round_index"?: number;
  "round_max"?: number;
  "streak"?: number;
  "threshold"?: number;
  "text"?: string;
  "operator_alert"?: boolean;
}

export interface EngineerSkillMaintenanceCompletedEvent extends EventMsg {
  type: "engineer.skill_maintenance.completed";
  payload_schema_version?: 1;
}

export interface LifeStatusEvent extends EventMsg {
  type: "life.status";
  payload_schema_version?: 1;
  "text"?: string;
}

export interface LifePhaseStartedEvent extends EventMsg {
  type: "life.phase.started";
  payload_schema_version?: 1;
  "agent_layer"?: string;
  "item_id"?: string;
  "round_index"?: number;
  "phase"?: string;
  "label"?: string;
}

export interface LifeMissionFailedEvent extends EventMsg {
  type: "life.mission.failed";
  payload_schema_version?: 1;
  "item_id"?: string;
  "title"?: string;
  "reason"?: string;
  "error"?: string;
  "outcome_class"?: "failed";
}

export interface LifeMissionSkippedEvent extends EventMsg {
  type: "life.mission.skipped";
  payload_schema_version?: 1;
  "item_id"?: string;
  "title"?: string;
  "reason"?: string;
}

export interface LifeMissionOrphanedEvent extends EventMsg {
  type: "life.mission.orphaned";
  payload_schema_version?: 1;
  "item_id"?: string;
  "title"?: string;
  "started_ts"?: number | null;
  "error"?: string;
}

export interface LifeMissionRequeuedEvent extends EventMsg {
  type: "life.mission.requeued";
  payload_schema_version?: 1;
  "item_id"?: string;
  "title"?: string;
  "started_ts"?: number | null;
  "error"?: string;
}

export interface LifeManagerIntentStartedEvent extends EventMsg {
  type: "life.manager.intent.started";
  payload_schema_version?: 1;
  "agent_layer"?: string;
  "intent_id"?: string;
  "item_id"?: string;
  "objective"?: string;
  "source"?: string;
  "text"?: string;
}

export interface LifeManagerStageDecisionEvent extends EventMsg {
  type: "life.manager.stage_decision";
  payload_schema_version?: 1;
  "action"?: string;
  "current_stage"?: string;
  "target_stage"?: string;
  "reason"?: string;
  "item_id"?: string;
  "source"?: string;
  "trigger"?: string;
  "resolves_wait"?: boolean;
}

export interface LifeVerticalResolvedEvent extends EventMsg {
  type: "life.vertical.resolved";
  payload_schema_version?: 1;
  "agent_layer"?: string;
  "vertical"?: string;
  "profile_hint"?: string;
}

export interface LifePlannerNormalizedEvent extends EventMsg {
  type: "life.planner.normalized";
  payload_schema_version?: 1;
  "cycle"?: number;
  "diagnostic"?: string;
}

export interface LifePlannerWaitingEvent extends EventMsg {
  type: "life.planner.waiting";
  payload_schema_version?: 1;
  "cycle"?: number;
  "reason"?: string;
  "consecutive_idle_cycles"?: number;
  "suggested_sleep_s"?: number;
  "model_call_skipped"?: boolean;
  "wait_mode"?: string;
  "waiting_contract_persisted"?: boolean;
  "waiting_contract"?: { "wait_id"?: string; "recheck_condition"?: string; "wait_mode"?: string; "wake_on"?: Array<string>; "observed_revision"?: string | null; } | null;
}

export interface LifePlannerWaitingWokenEvent extends EventMsg {
  type: "life.planner.waiting_woken";
  payload_schema_version?: 1;
  "blocker_fingerprint"?: string;
  "recheck_token"?: string;
  "wake_reason"?: string;
  "observed_revision"?: string | null;
  "current_revision"?: string | null;
}

export interface LifePlannerTerminalIdleEvent extends EventMsg {
  type: "life.planner.terminal_idle";
  payload_schema_version?: 1;
  "cycle"?: number;
  "reason"?: string;
  "consecutive_idle_cycles"?: number;
  "suggested_sleep_s"?: number;
}

export interface LifePlannerVerificationProbeEvent extends EventMsg {
  type: "life.planner.verification_probe";
  payload_schema_version?: 1;
  "cycle"?: number;
  "idle_cycles"?: number;
  "reason"?: string;
  "waiting_contract"?: Record<string, unknown> | null;
}

export interface LifePlannerStallEscalationEvent extends EventMsg {
  type: "life.planner.stall_escalation";
  payload_schema_version?: 1;
  "objective"?: string;
  "consecutive_no_progress_missions"?: number;
  "reason"?: string;
  "text"?: string;
}

export interface LifePlanRevisionProposedEvent extends EventMsg {
  type: "life.plan.revision.proposed";
  payload_schema_version?: 1;
  "expected_plan_id"?: string;
  "expected_plan_version"?: number;
  "trigger_item_id"?: string;
  "active_item_ids"?: Array<string>;
  "reason"?: string;
}

export interface LifePlanRevisionRejectedEvent extends EventMsg {
  type: "life.plan.revision.rejected";
  payload_schema_version?: 1;
  "expected_plan_id"?: string;
  "expected_plan_version"?: number;
  "item_id"?: string;
  "trigger_status"?: string;
  "attempts"?: number;
  "terminal"?: boolean;
  "reason"?: string;
}

export interface LifePlanRevisionCommittedEvent extends EventMsg {
  type: "life.plan.revision.committed";
  payload_schema_version?: 1;
  "old_plan_id"?: string;
  "old_plan_version"?: number;
  "new_plan_id"?: string;
  "new_plan_version"?: number;
  "added_item_ids"?: Array<string>;
  "superseded_item_ids"?: Array<string>;
  "manager_action"?: string;
  "challenge"?: string;
  "alternative"?: string;
  "revision_latency_seconds"?: number;
}

export interface LifePlanNodeSupersededEvent extends EventMsg {
  type: "life.plan.node.superseded";
  payload_schema_version?: 1;
  "item_id"?: string;
  "plan_id"?: string;
  "plan_version"?: number;
  "superseded_by_plan_id"?: string;
  "reason"?: string;
  "source"?: string;
}

export interface LifeBudgetPauseEvent extends EventMsg {
  type: "life.budget.pause";
  payload_schema_version?: 1;
  "agent_layer"?: string;
  "item_id"?: string;
  "title"?: string;
  "reason"?: string;
  "text"?: string;
}

export interface LifeLifecycleBlockEvent extends EventMsg {
  type: "life.lifecycle.block";
  payload_schema_version?: 1;
  "agent_layer"?: string;
  "item_id"?: string;
  "title"?: string;
  "lifecycle_state"?: string;
  "reason"?: string;
  "text"?: string;
}

export interface LifeLifecycleTransitionEvent extends EventMsg {
  type: "life.lifecycle.transition";
  payload_schema_version?: 1;
  "agent_layer"?: string;
  "from_state"?: string;
  "to_state"?: string;
  "reason"?: string;
}

export interface LifeInboxQueuedEvent extends EventMsg {
  type: "life.inbox.queued";
  payload_schema_version?: 1;
  "source"?: string;
  "stage"?: string;
  "text"?: string;
}

export interface LifeDaemonIdleTimeoutEvent extends EventMsg {
  type: "life.daemon.idle_timeout";
  payload_schema_version?: 1;
  "agent_layer"?: string;
  "idle_seconds"?: number;
  "text"?: string;
}

export interface DaemonParkedEvent extends EventMsg {
  type: "daemon.parked";
  payload_schema_version?: 1;
  "previous_pid"?: number;
  "replaced_by"?: string | null;
  "state_preserved"?: boolean;
  "unfinished_tasks"?: number;
}

export interface IdeaSearchStartedEvent extends EventMsg {
  type: "idea.search.started";
  payload_schema_version?: 1;
  "text"?: string;
}

export interface IdeaSearchCompletedEvent extends EventMsg {
  type: "idea.search.completed";
  payload_schema_version?: 1;
  "count"?: number;
  "text"?: string;
}

export interface IdeaSearchSkippedEvent extends EventMsg {
  type: "idea.search.skipped";
  payload_schema_version?: 1;
  "reason"?: string;
  "text"?: string;
}

export interface VenueResearchStartedEvent extends EventMsg {
  type: "venue.research.started";
  payload_schema_version?: 1;
  "text"?: string;
}

export interface VenueResearchCompletedEvent extends EventMsg {
  type: "venue.research.completed";
  payload_schema_version?: 1;
  "ok"?: boolean;
  "text"?: string;
}

export interface SkillLibraryAvailableEvent extends EventMsg {
  type: "skill.library.available";
  payload_schema_version?: 1;
  "role"?: string;
  "paths"?: Array<string>;
  "own_paths"?: Array<string>;
  "reference_paths"?: Array<string>;
  "required_paths"?: Array<string>;
  "precedence"?: Array<string>;
  "discovery"?: string;
  "text"?: string;
}

export interface OperatorAlertEvent extends EventMsg {
  type: "operator_alert";
  payload_schema_version?: 1;
  "text"?: string;
  "reason"?: string;
  "operator_alert"?: true;
}

export interface EventPayloadByType {
  "agent.io.start": AgentIoStartEvent;
  "agent.io.stream": AgentIoStreamEvent;
  "agent.io.complete": AgentIoCompleteEvent;
  "agent.io.error": AgentIoErrorEvent;
  "usage.recorded": UsageRecordedEvent;
  "provider.request.started": ProviderRequestStartedEvent;
  "provider.request.completed": ProviderRequestCompletedEvent;
  "provider.request.denied": ProviderRequestDeniedEvent;
  "budget.reservation.created": BudgetReservationCreatedEvent;
  "budget.reservation.denied": BudgetReservationDeniedEvent;
  "budget.reservation.settled": BudgetReservationSettledEvent;
  "budget.reservation.released": BudgetReservationReleasedEvent;
  "budget.unpriced.blocked": BudgetUnpricedBlockedEvent;
  "life.mission.started": LifeMissionStartedEvent;
  "life.mission.completed": LifeMissionCompletedEvent;
  "round.start": RoundStartEvent;
  "round.main.completed": RoundMainCompletedEvent;
  "round.review.started": RoundReviewStartedEvent;
  "round.review.deferred": RoundReviewDeferredEvent;
  "round.review.completed": RoundReviewCompletedEvent;
  "round.secret_redacted": RoundSecretRedactedEvent;
  "life.planner.start": LifePlannerStartEvent;
  "life.planner.verdict": LifePlannerVerdictEvent;
  "life.planner.error": LifePlannerErrorEvent;
  "life.runtime_failure.circuit_opened": LifeRuntimeFailureCircuitOpenedEvent;
  "life.runtime_failure.circuit_blocked": LifeRuntimeFailureCircuitBlockedEvent;
  "life.runtime_failure.canary_passed": LifeRuntimeFailureCanaryPassedEvent;
  "life.planner.task_added": LifePlannerTaskAddedEvent;
  "life.planner.task_skipped": LifePlannerTaskSkippedEvent;
  "life.manager.intent.completed": LifeManagerIntentCompletedEvent;
  "life.manager.intent.failed": LifeManagerIntentFailedEvent;
  "life.manager.plan_challenge.decided": LifeManagerPlanChallengeDecidedEvent;
  "life.inbox.drained": LifeInboxDrainedEvent;
  "life.operator_question.pending": LifeOperatorQuestionPendingEvent;
  "life.operator_question.answered": LifeOperatorQuestionAnsweredEvent;
  "role.session.turn": RoleSessionTurnEvent;
  "engineer.progress": EngineerProgressEvent;
  "skill.created": SkillCreatedEvent;
  "skill.updated": SkillUpdatedEvent;
  "skill.archived": SkillArchivedEvent;
  "skill.cost.completed": SkillCostCompletedEvent;
  "skill.tidied": SkillTidiedEvent;
  "skill.history.compressed": SkillHistoryCompressedEvent;
  "skill.evolution.completed": SkillEvolutionCompletedEvent;
  "wiki.initialized": WikiInitializedEvent;
  "wiki.hook.warning": WikiHookWarningEvent;
  "wiki.created": WikiCreatedEvent;
  "wiki.updated": WikiUpdatedEvent;
  "wiki.retired": WikiRetiredEvent;
  "wiki.promotion.promoted": WikiPromotionPromotedEvent;
  "wiki.promotion.demoted": WikiPromotionDemotedEvent;
  "wiki.retired.compressed": WikiRetiredCompressedEvent;
  "wiki.evolution.completed": WikiEvolutionCompletedEvent;
  "project.completed": ProjectCompletedEvent;
  "project.completion_refused": ProjectCompletionRefusedEvent;
  "research.achievement.certified": ResearchAchievementCertifiedEvent;
  "daemon.command.submitted": DaemonCommandSubmittedEvent;
  "daemon.command.completed": DaemonCommandCompletedEvent;
  "daemon.command.rejected": DaemonCommandRejectedEvent;
  "life.manager.backend_resolved": LifeManagerBackendResolvedEvent;
  "life.planner.backend_resolved": LifePlannerBackendResolvedEvent;
  "life.engineer.backend_resolved": LifeEngineerBackendResolvedEvent;
  "life.reviewer.backend_resolved": LifeReviewerBackendResolvedEvent;
  "life.curator.backend_resolved": LifeCuratorBackendResolvedEvent;
  "codex.util.completed": CodexUtilCompletedEvent;
  "loop.start": LoopStartEvent;
  "loop.done": LoopDoneEvent;
  "round.checkpoint.recorded": RoundCheckpointRecordedEvent;
  "round.checkpoint.failed": RoundCheckpointFailedEvent;
  "round.escalated": RoundEscalatedEvent;
  "round.stall": RoundStallEvent;
  "round.reviewer_backend_failure": RoundReviewerBackendFailureEvent;
  "engineer.skill_maintenance.completed": EngineerSkillMaintenanceCompletedEvent;
  "life.status": LifeStatusEvent;
  "life.phase.started": LifePhaseStartedEvent;
  "life.mission.failed": LifeMissionFailedEvent;
  "life.mission.skipped": LifeMissionSkippedEvent;
  "life.mission.orphaned": LifeMissionOrphanedEvent;
  "life.mission.requeued": LifeMissionRequeuedEvent;
  "life.manager.intent.started": LifeManagerIntentStartedEvent;
  "life.manager.stage_decision": LifeManagerStageDecisionEvent;
  "life.vertical.resolved": LifeVerticalResolvedEvent;
  "life.planner.normalized": LifePlannerNormalizedEvent;
  "life.planner.waiting": LifePlannerWaitingEvent;
  "life.planner.waiting_woken": LifePlannerWaitingWokenEvent;
  "life.planner.terminal_idle": LifePlannerTerminalIdleEvent;
  "life.planner.verification_probe": LifePlannerVerificationProbeEvent;
  "life.planner.stall_escalation": LifePlannerStallEscalationEvent;
  "life.plan.revision.proposed": LifePlanRevisionProposedEvent;
  "life.plan.revision.rejected": LifePlanRevisionRejectedEvent;
  "life.plan.revision.committed": LifePlanRevisionCommittedEvent;
  "life.plan.node.superseded": LifePlanNodeSupersededEvent;
  "life.budget.pause": LifeBudgetPauseEvent;
  "life.lifecycle.block": LifeLifecycleBlockEvent;
  "life.lifecycle.transition": LifeLifecycleTransitionEvent;
  "life.inbox.queued": LifeInboxQueuedEvent;
  "life.daemon.idle_timeout": LifeDaemonIdleTimeoutEvent;
  "daemon.parked": DaemonParkedEvent;
  "idea.search.started": IdeaSearchStartedEvent;
  "idea.search.completed": IdeaSearchCompletedEvent;
  "idea.search.skipped": IdeaSearchSkippedEvent;
  "venue.research.started": VenueResearchStartedEvent;
  "venue.research.completed": VenueResearchCompletedEvent;
  "skill.library.available": SkillLibraryAvailableEvent;
  "operator_alert": OperatorAlertEvent;
}

export type TypedArgusEvent = EventPayloadByType[keyof EventPayloadByType];
