// Generated by scripts/generate_event_payload_types.py. Do not edit.
import type { EventMsg } from './types.js';

export const EVENT_PAYLOAD_SCHEMA_VERSION = 1;

export interface AgentIoStartEvent extends EventMsg {
  type: "agent.io.start";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label": string;
  "backend"?: string;
  "model"?: string | null;
  "working_dir"?: string | null;
  "resume_thread_id"?: string | null;
}

export interface AgentIoStreamEvent extends EventMsg {
  type: "agent.io.stream";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label"?: string | null;
  "stream": "stdout" | "stderr";
  "line": string;
}

export interface AgentIoCompleteEvent extends EventMsg {
  type: "agent.io.complete";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label": string;
  "backend"?: string;
  "model"?: string | null;
  "exit_code"?: number | null;
  "thread_id"?: string | null;
  "fatal_error"?: string | null;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "cache_write_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "premium_requests"?: number;
  "total_nano_aiu"?: number | null;
}

export interface AgentIoErrorEvent extends EventMsg {
  type: "agent.io.error";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label"?: string;
  "backend"?: string;
  "error": string;
}

export interface UsageRecordedEvent extends EventMsg {
  type: "usage.recorded";
  payload_schema_version?: 2;
  "call_id": string;
  "schema_version": 2;
  "project_id"?: string;
  "mission_id"?: string | null;
  "thread_id"?: string | null;
  "provider": string;
  "model"?: string;
  "run_label"?: string;
  "status": "completed" | "error" | "denied";
  "duration_ms"?: number;
  "usage": Record<string, unknown>;
  "pricing": Record<string, unknown>;
}

export interface ProviderRequestStartedEvent extends EventMsg {
  type: "provider.request.started";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "daily_calls"?: number;
  "daily_cap"?: number;
}

export interface ProviderRequestCompletedEvent extends EventMsg {
  type: "provider.request.completed";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "success"?: boolean;
  "error"?: string;
  "premium_requests"?: number;
}

export interface ProviderRequestDeniedEvent extends EventMsg {
  type: "provider.request.denied";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "reason"?: string;
}

export interface BudgetReservationCreatedEvent extends EventMsg {
  type: "budget.reservation.created";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd": number;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface BudgetReservationDeniedEvent extends EventMsg {
  type: "budget.reservation.denied";
  payload_schema_version?: 1;
  "call_id": string;
  "reason": string;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface BudgetReservationSettledEvent extends EventMsg {
  type: "budget.reservation.settled";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd"?: number;
  "cost_usd"?: number | null;
  "overrun_usd"?: number | null;
  "pricing_status": string;
}

export interface BudgetReservationReleasedEvent extends EventMsg {
  type: "budget.reservation.released";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd"?: number;
  "reason"?: string;
}

export interface BudgetUnpricedBlockedEvent extends EventMsg {
  type: "budget.unpriced.blocked";
  payload_schema_version?: 1;
  "call_id": string;
  "reason": string;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface LifeMissionStartedEvent extends EventMsg {
  type: "life.mission.started";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
  "missions_started"?: number;
}

export interface LifeMissionCompletedEvent extends EventMsg {
  type: "life.mission.completed";
  payload_schema_version?: 1;
  "item_id": string;
  "status": string;
  "success"?: boolean;
  "cost_usd"?: number | null;
  "known_cost_usd"?: number;
  "pricing_status"?: string;
}

export interface RoundStartEvent extends EventMsg {
  type: "round.start";
  payload_schema_version?: 1;
  "round_index": number;
  "round_max"?: number;
  "session_id"?: string | null;
}

export interface RoundMainCompletedEvent extends EventMsg {
  type: "round.main.completed";
  payload_schema_version?: 1;
  "round_index": number;
  "exit_code"?: number;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
}

export interface RoundReviewStartedEvent extends EventMsg {
  type: "round.review.started";
  payload_schema_version?: 1;
  "round_index": number;
  "status"?: string;
}

export interface RoundReviewCompletedEvent extends EventMsg {
  type: "round.review.completed";
  payload_schema_version?: 1;
  "round_index"?: number;
  "status": "done" | "continue" | "blocked";
  "reason": string;
  "next_action"?: string;
  "scope"?: string;
  "checklist"?: Array<Record<string, unknown>>;
  "planner_report"?: Record<string, unknown>;
  "checkpoint"?: Record<string, unknown>;
}

export interface LifePlannerStartEvent extends EventMsg {
  type: "life.planner.start";
  payload_schema_version?: 1;
  "manager_intent"?: Record<string, unknown>;
  "cycle"?: number;
}

export interface LifePlannerVerdictEvent extends EventMsg {
  type: "life.planner.verdict";
  payload_schema_version?: 1;
  "status": string;
  "reason"?: string;
  "tasks_added"?: number;
}

export interface LifePlannerErrorEvent extends EventMsg {
  type: "life.planner.error";
  payload_schema_version?: 1;
  "error": string;
  "reason"?: string;
}

export interface LifePlannerTaskAddedEvent extends EventMsg {
  type: "life.planner.task_added";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
}

export interface LifePlannerTaskSkippedEvent extends EventMsg {
  type: "life.planner.task_skipped";
  payload_schema_version?: 1;
  "item_id"?: string;
  "title"?: string;
  "reason": string;
}

export interface DaemonCommandSubmittedEvent extends EventMsg {
  type: "daemon.command.submitted";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "revision": number;
  "expected_revision"?: number | null;
}

export interface DaemonCommandCompletedEvent extends EventMsg {
  type: "daemon.command.completed";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "status": "applied" | "failed";
  "revision": number;
  "error"?: string;
  "result"?: Record<string, unknown>;
}

export interface DaemonCommandRejectedEvent extends EventMsg {
  type: "daemon.command.rejected";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "status": "rejected";
  "revision": number;
  "error": string;
}

export interface EventPayloadByType {
  "agent.io.start": AgentIoStartEvent;
  "agent.io.stream": AgentIoStreamEvent;
  "agent.io.complete": AgentIoCompleteEvent;
  "agent.io.error": AgentIoErrorEvent;
  "usage.recorded": UsageRecordedEvent;
  "provider.request.started": ProviderRequestStartedEvent;
  "provider.request.completed": ProviderRequestCompletedEvent;
  "provider.request.denied": ProviderRequestDeniedEvent;
  "budget.reservation.created": BudgetReservationCreatedEvent;
  "budget.reservation.denied": BudgetReservationDeniedEvent;
  "budget.reservation.settled": BudgetReservationSettledEvent;
  "budget.reservation.released": BudgetReservationReleasedEvent;
  "budget.unpriced.blocked": BudgetUnpricedBlockedEvent;
  "life.mission.started": LifeMissionStartedEvent;
  "life.mission.completed": LifeMissionCompletedEvent;
  "round.start": RoundStartEvent;
  "round.main.completed": RoundMainCompletedEvent;
  "round.review.started": RoundReviewStartedEvent;
  "round.review.completed": RoundReviewCompletedEvent;
  "life.planner.start": LifePlannerStartEvent;
  "life.planner.verdict": LifePlannerVerdictEvent;
  "life.planner.error": LifePlannerErrorEvent;
  "life.planner.task_added": LifePlannerTaskAddedEvent;
  "life.planner.task_skipped": LifePlannerTaskSkippedEvent;
  "daemon.command.submitted": DaemonCommandSubmittedEvent;
  "daemon.command.completed": DaemonCommandCompletedEvent;
  "daemon.command.rejected": DaemonCommandRejectedEvent;
}

export type TypedArgusEvent = EventPayloadByType[keyof EventPayloadByType];
