// Generated by scripts/generate_event_payload_types.py. Do not edit.
import type { EventMsg } from './types.js';

export const EVENT_PAYLOAD_SCHEMA_VERSION = 1;

export interface AgentIoStartEvent extends EventMsg {
  type: "agent.io.start";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label": string;
  "backend"?: string;
  "model"?: string | null;
  "working_dir"?: string | null;
  "resume_thread_id"?: string | null;
}

export interface AgentIoStreamEvent extends EventMsg {
  type: "agent.io.stream";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label"?: string | null;
  "stream": "stdout" | "stderr";
  "line": string;
}

export interface AgentIoCompleteEvent extends EventMsg {
  type: "agent.io.complete";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label": string;
  "backend"?: string;
  "model"?: string | null;
  "exit_code"?: number | null;
  "thread_id"?: string | null;
  "fatal_error"?: string | null;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "cache_write_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "premium_requests"?: number;
  "total_nano_aiu"?: number | null;
}

export interface AgentIoErrorEvent extends EventMsg {
  type: "agent.io.error";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label"?: string;
  "backend"?: string;
  "error": string;
}

export interface UsageRecordedEvent extends EventMsg {
  type: "usage.recorded";
  payload_schema_version?: 2;
  "call_id": string;
  "schema_version": 2;
  "project_id"?: string;
  "mission_id"?: string | null;
  "thread_id"?: string | null;
  "provider": string;
  "model"?: string;
  "run_label"?: string;
  "status": "completed" | "error" | "denied";
  "duration_ms"?: number;
  "usage": Record<string, unknown>;
  "pricing": Record<string, unknown>;
}

export interface ProviderRequestStartedEvent extends EventMsg {
  type: "provider.request.started";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "daily_calls"?: number;
  "daily_cap"?: number;
}

export interface ProviderRequestCompletedEvent extends EventMsg {
  type: "provider.request.completed";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "success"?: boolean;
  "error"?: string;
  "premium_requests"?: number;
}

export interface ProviderRequestDeniedEvent extends EventMsg {
  type: "provider.request.denied";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "reason"?: string;
}

export interface BudgetReservationCreatedEvent extends EventMsg {
  type: "budget.reservation.created";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd": number;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
  "fence_enforcement"?: "hard" | "soft" | "unsupported" | "none";
  "fence_limit_usd"?: number | null;
  "fence_limit_ai_credits"?: number | null;
  "fence_reason"?: string;
}

export interface BudgetReservationDeniedEvent extends EventMsg {
  type: "budget.reservation.denied";
  payload_schema_version?: 1;
  "call_id": string;
  "reason": string;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface BudgetReservationSettledEvent extends EventMsg {
  type: "budget.reservation.settled";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd"?: number;
  "cost_usd"?: number | null;
  "overrun_usd"?: number | null;
  "fence_breached"?: boolean;
  "fence_enforcement"?: "hard" | "soft" | "unsupported" | "none";
  "fence_limit_usd"?: number | null;
  "fence_limit_ai_credits"?: number | null;
  "fence_reason"?: string;
  "pricing_status": string;
}

export interface BudgetReservationReleasedEvent extends EventMsg {
  type: "budget.reservation.released";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd"?: number;
  "reason"?: string;
}

export interface BudgetUnpricedBlockedEvent extends EventMsg {
  type: "budget.unpriced.blocked";
  payload_schema_version?: 1;
  "call_id": string;
  "reason": string;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface LifeMissionStartedEvent extends EventMsg {
  type: "life.mission.started";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
  "missions_started"?: number;
}

export interface LifeMissionCompletedEvent extends EventMsg {
  type: "life.mission.completed";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
  "status": string;
  "success"?: boolean;
  "rounds"?: number;
  "elapsed_seconds"?: number;
  "cost_usd"?: number | null;
  "known_cost_usd"?: number;
  "pricing_status"?: string;
}

export interface RoundStartEvent extends EventMsg {
  type: "round.start";
  payload_schema_version?: 1;
  "round_index": number;
  "round_max"?: number;
  "session_id"?: string | null;
}

export interface RoundMainCompletedEvent extends EventMsg {
  type: "round.main.completed";
  payload_schema_version?: 1;
  "round_index": number;
  "exit_code"?: number;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
}

export interface RoundReviewStartedEvent extends EventMsg {
  type: "round.review.started";
  payload_schema_version?: 1;
  "round_index": number;
  "status"?: string;
}

export interface RoundReviewCompletedEvent extends EventMsg {
  type: "round.review.completed";
  payload_schema_version?: 1;
  "round_index"?: number;
  "status": "done" | "continue" | "blocked";
  "reason": string;
  "next_action"?: string;
  "scope"?: string;
  "checklist"?: Array<Record<string, unknown>>;
  "planner_report"?: Record<string, unknown>;
  "checkpoint"?: Record<string, unknown>;
}

export interface LifePlannerStartEvent extends EventMsg {
  type: "life.planner.start";
  payload_schema_version?: 1;
  "manager_intent"?: Record<string, unknown>;
  "cycle"?: number;
}

export interface LifePlannerVerdictEvent extends EventMsg {
  type: "life.planner.verdict";
  payload_schema_version?: 1;
  "status": string;
  "reason"?: string;
  "tasks_added"?: number;
}

export interface LifePlannerErrorEvent extends EventMsg {
  type: "life.planner.error";
  payload_schema_version?: 1;
  "error": string;
  "reason"?: string;
}

export interface LifePlannerTaskAddedEvent extends EventMsg {
  type: "life.planner.task_added";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
  "deps"?: Array<string>;
  "priority"?: number;
  "impact_score"?: number;
  "impact_area"?: string;
  "branch_id"?: string;
  "parent_branch_id"?: string | null;
}

export interface LifePlannerTaskSkippedEvent extends EventMsg {
  type: "life.planner.task_skipped";
  payload_schema_version?: 1;
  "item_id"?: string;
  "title"?: string;
  "reason": string;
}

export interface LifeManagerIntentCompletedEvent extends EventMsg {
  type: "life.manager.intent.completed";
  payload_schema_version?: 1;
  "intent_id": string;
  "item_id": string;
  "objective": string;
  "vertical": string;
  "kind": string;
  "stages": Array<string>;
  "reason"?: string;
}

export interface EngineerProgressEvent extends EventMsg {
  type: "engineer.progress";
  payload_schema_version?: 1;
  "kind": string;
  "text"?: string;
  "actor"?: string;
  "agent_layer"?: string;
  "message_id"?: string;
  "replace"?: boolean;
  "round_index"?: number;
  "experiment_id"?: string;
  "branch_id"?: string;
}

export interface SkillCreatedEvent extends EventMsg {
  type: "skill.created";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "name"?: string;
  "version"?: number;
  "scope"?: string;
  "path"?: string;
  "text"?: string;
}

export interface SkillUpdatedEvent extends EventMsg {
  type: "skill.updated";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "name"?: string;
  "version"?: number;
  "scope"?: string;
  "path"?: string;
  "text"?: string;
}

export interface SkillArchivedEvent extends EventMsg {
  type: "skill.archived";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "name"?: string;
  "version"?: number;
  "scope"?: string;
  "path"?: string;
  "reason"?: string;
  "text"?: string;
}

export interface SkillEvolutionCompletedEvent extends EventMsg {
  type: "skill.evolution.completed";
  payload_schema_version?: 1;
  "ops_proposed": number;
  "created": number;
  "updated": number;
  "archived": number;
  "rejected": number;
  "compaction_clusters"?: number;
  "compacted"?: number;
  "errors"?: number;
  "text"?: string;
}

export interface WikiInitializedEvent extends EventMsg {
  type: "wiki.initialized";
  payload_schema_version?: 1;
  "project": string;
  "path": string;
  "auto": boolean;
  "text"?: string;
}

export interface WikiInitializationFailedEvent extends EventMsg {
  type: "wiki.initialization.failed";
  payload_schema_version?: 1;
  "workdir": string;
  "error": string;
  "text"?: string;
}

export interface WikiEvolutionCompletedEvent extends EventMsg {
  type: "wiki.evolution.completed";
  payload_schema_version?: 1;
  "wiki_count": number;
  "ops_proposed": number;
  "sources"?: number;
  "scratch_pages"?: number;
  "created"?: number;
  "updated"?: number;
  "retired"?: number;
  "skipped"?: number;
  "rejected"?: number;
  "promoted"?: number;
  "demoted"?: number;
  "compaction_clusters"?: number;
  "compacted"?: number;
  "errors"?: number;
  "paths"?: Array<string>;
  "text"?: string;
}

export interface ResearchHypothesisProposedEvent extends EventMsg {
  type: "research.hypothesis.proposed";
  payload_schema_version?: 1;
  "hypothesis_id": string;
  "title": string;
  "statement": string;
  "branch_id"?: string;
  "parent_branch_id"?: string | null;
  "evidence"?: Array<string>;
  "item_id"?: string;
  "round_index"?: number;
}

export interface ResearchExperimentStartedEvent extends EventMsg {
  type: "research.experiment.started";
  payload_schema_version?: 1;
  "experiment_id": string;
  "title": string;
  "hypothesis_id"?: string;
  "branch_id"?: string;
  "item_id"?: string;
  "round_index"?: number;
  "summary"?: string;
}

export interface ResearchExperimentCompletedEvent extends EventMsg {
  type: "research.experiment.completed";
  payload_schema_version?: 1;
  "experiment_id": string;
  "status": "completed" | "failed" | "cancelled";
  "hypothesis_id"?: string;
  "branch_id"?: string;
  "item_id"?: string;
  "round_index"?: number;
  "summary"?: string;
  "duration_seconds"?: number;
  "evidence"?: Array<string>;
}

export interface ResearchMetricReportedEvent extends EventMsg {
  type: "research.metric.reported";
  payload_schema_version?: 1;
  "metric_id": string;
  "name": string;
  "baseline"?: number | null;
  "value": number;
  "unit"?: string;
  "direction": "maximize" | "minimize" | "target";
  "evidence": string;
  "experiment_id"?: string;
  "hypothesis_id"?: string;
  "branch_id"?: string;
  "item_id"?: string;
  "round_index"?: number;
  "primary"?: boolean;
}

export interface ResearchMetricVerifiedEvent extends EventMsg {
  type: "research.metric.verified";
  payload_schema_version?: 1;
  "metric_id": string;
  "status": "accepted" | "rejected";
  "reviewer_reason": string;
  "evidence"?: string;
  "round_index"?: number;
}

export interface ResearchArtifactRegisteredEvent extends EventMsg {
  type: "research.artifact.registered";
  payload_schema_version?: 1;
  "artifact_id": string;
  "path": string;
  "kind": "text" | "image" | "pdf" | "data" | "code" | "binary";
  "title"?: string;
  "why"?: string;
  "experiment_id"?: string;
  "branch_id"?: string;
  "item_id"?: string;
  "round_index"?: number;
}

export interface ResearchAchievementCertifiedEvent extends EventMsg {
  type: "research.achievement.certified";
  payload_schema_version?: 1;
  "achievement_id": string;
  "title": string;
  "goal": string;
  "metric_id"?: string;
  "summary"?: string;
  "evidence"?: Array<string>;
  "reviewer_certified": true;
}

export interface DaemonCommandSubmittedEvent extends EventMsg {
  type: "daemon.command.submitted";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "revision": number;
  "expected_revision"?: number | null;
}

export interface DaemonCommandCompletedEvent extends EventMsg {
  type: "daemon.command.completed";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "status": "applied" | "failed";
  "revision": number;
  "error"?: string;
  "result"?: Record<string, unknown>;
}

export interface DaemonCommandRejectedEvent extends EventMsg {
  type: "daemon.command.rejected";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "status": "rejected";
  "revision": number;
  "error": string;
}

export interface EventPayloadByType {
  "agent.io.start": AgentIoStartEvent;
  "agent.io.stream": AgentIoStreamEvent;
  "agent.io.complete": AgentIoCompleteEvent;
  "agent.io.error": AgentIoErrorEvent;
  "usage.recorded": UsageRecordedEvent;
  "provider.request.started": ProviderRequestStartedEvent;
  "provider.request.completed": ProviderRequestCompletedEvent;
  "provider.request.denied": ProviderRequestDeniedEvent;
  "budget.reservation.created": BudgetReservationCreatedEvent;
  "budget.reservation.denied": BudgetReservationDeniedEvent;
  "budget.reservation.settled": BudgetReservationSettledEvent;
  "budget.reservation.released": BudgetReservationReleasedEvent;
  "budget.unpriced.blocked": BudgetUnpricedBlockedEvent;
  "life.mission.started": LifeMissionStartedEvent;
  "life.mission.completed": LifeMissionCompletedEvent;
  "round.start": RoundStartEvent;
  "round.main.completed": RoundMainCompletedEvent;
  "round.review.started": RoundReviewStartedEvent;
  "round.review.completed": RoundReviewCompletedEvent;
  "life.planner.start": LifePlannerStartEvent;
  "life.planner.verdict": LifePlannerVerdictEvent;
  "life.planner.error": LifePlannerErrorEvent;
  "life.planner.task_added": LifePlannerTaskAddedEvent;
  "life.planner.task_skipped": LifePlannerTaskSkippedEvent;
  "life.manager.intent.completed": LifeManagerIntentCompletedEvent;
  "engineer.progress": EngineerProgressEvent;
  "skill.created": SkillCreatedEvent;
  "skill.updated": SkillUpdatedEvent;
  "skill.archived": SkillArchivedEvent;
  "skill.evolution.completed": SkillEvolutionCompletedEvent;
  "wiki.initialized": WikiInitializedEvent;
  "wiki.initialization.failed": WikiInitializationFailedEvent;
  "wiki.evolution.completed": WikiEvolutionCompletedEvent;
  "research.hypothesis.proposed": ResearchHypothesisProposedEvent;
  "research.experiment.started": ResearchExperimentStartedEvent;
  "research.experiment.completed": ResearchExperimentCompletedEvent;
  "research.metric.reported": ResearchMetricReportedEvent;
  "research.metric.verified": ResearchMetricVerifiedEvent;
  "research.artifact.registered": ResearchArtifactRegisteredEvent;
  "research.achievement.certified": ResearchAchievementCertifiedEvent;
  "daemon.command.submitted": DaemonCommandSubmittedEvent;
  "daemon.command.completed": DaemonCommandCompletedEvent;
  "daemon.command.rejected": DaemonCommandRejectedEvent;
}

export type TypedArgusEvent = EventPayloadByType[keyof EventPayloadByType];
