// Generated by argus.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.7+60b0bbb7e1811d7f";
export const RELEASE_SOURCE_DIGEST = "60b0bbb7e1811d7f1a6ac0f298e69efc9ac54b1e285b7902372c508e580256cf";
