// Generated by scripts/generate_release_manifest.py. Do not edit.
export const RELEASE_ID = "0.1.0+69e098f004e31c53";
export const RELEASE_SOURCE_DIGEST = "69e098f004e31c53e988b01414fd76f63f2e992f002180fe29c48d1b46654703";
