// Generated by scripts/generate_release_manifest.py. Do not edit.
export const RELEASE_ID = "0.1.1+eb04e73a74cea934";
export const RELEASE_SOURCE_DIGEST = "eb04e73a74cea9343e0efba8b858119a501ca75d6f8a9d119b7a2c73f41853c9";
