// Generated by argus_skill.release_tools.generate_resource_status. Do not edit.

export interface ResourceAcceleratorStatus {
  readonly "kind": string;
  readonly "status": "available" | "absent" | "inaccessible" | "degraded";
  readonly "device_count": number;
  readonly "detail": string;
}

export interface ResourceYieldResponse {
  readonly "decision": "decline" | "yield";
  readonly "reason": string;
}

export interface ResourceYieldRequest {
  readonly "reason": string;
  readonly "response": ResourceYieldResponse | null;
}

export interface ResourceHolderStatus {
  readonly "project": string;
  readonly "task_id": string;
  readonly "intent": string;
  readonly "ttl_seconds": number;
  readonly "device_count": number;
  readonly "yield_requests": ReadonlyArray<ResourceYieldRequest>;
}

export interface ResourceQueueStatus {
  readonly "position": number;
  readonly "project": string;
  readonly "task_id": string;
  readonly "intent": string;
  readonly "ttl_seconds": number;
}

export interface ResourceStatus {
  readonly "schema_version": 1;
  readonly "enforcement": "strict" | "advisory";
  readonly "accelerators": ReadonlyArray<ResourceAcceleratorStatus>;
  readonly "holders": ReadonlyArray<ResourceHolderStatus>;
  readonly "queue": ReadonlyArray<ResourceQueueStatus>;
}
