#!/usr/bin/env python3
"""Grade only Reviewer-approved MLE submissions and return leaderboard feedback.

The agent never receives private labels or the private data path. It receives
only the same aggregate report a human competitor would see after submitting.
"""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import os
import shutil
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent


def load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    for raw in (HERE / "config.env").read_text().splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            key, value = line.split("=", 1)
            env[key] = value
    return env


CFG = load_env()
CAMPAIGN_ROOT = Path(CFG["CAMPAIGN_ROOT"])
DATA_ROOT = Path(CFG["DATA_ROOT"])
ARGUS_HOME = Path(CFG["ARGUS_HOME"])
ARGUS_BIN = CFG["ARGUS_BIN"]
MLEBENCH_REPO = Path(CFG["MLEBENCH_REPO"])
MLEBENCH_BIN = Path(CFG["MLEBENCH_BIN"])
MLEBENCH_PYTHON = MLEBENCH_BIN.parent / "python"
GRADE_ROOT = CAMPAIGN_ROOT / "grades"
HISTORY = GRADE_ROOT / "reviewer-approved-history.jsonl"
STATE = GRADE_ROOT / "reviewer-approved-state.json"
LOCK = GRADE_ROOT / "reviewer-approved-watcher.lock"
COMPETITION_LIST = Path(CFG.get("COMPETITION_LIST", str(HERE / "lite.txt")))

GRADE_SNIPPET = r"""
import json
import sys
from pathlib import Path
from mlebench.grade import grade_csv
from mlebench.registry import registry

submission, competition_id, data_dir = sys.argv[1:]
competition = registry.set_data_dir(Path(data_dir)).get_competition(competition_id)
report = grade_csv(Path(submission), competition)

def encode(value):
    if hasattr(value, "item"):
        return value.item()
    return str(value)

print("__MLE_REPORT__" + json.dumps(report.to_dict(), sort_keys=True, default=encode))
"""


def utc_iso(epoch: float | None = None) -> str:
    dt = datetime.fromtimestamp(epoch or time.time(), tz=timezone.utc)
    return dt.isoformat().replace("+00:00", "Z")


def atomic_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(value, indent=2, sort_keys=True, default=str) + "\n")
    os.replace(tmp, path)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_history() -> list[dict[str, Any]]:
    if not HISTORY.exists():
        return []
    rows: list[dict[str, Any]] = []
    for line in HISTORY.read_text(errors="replace").splitlines():
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return rows


def append_history(entry: dict[str, Any]) -> None:
    HISTORY.parent.mkdir(parents=True, exist_ok=True)
    with HISTORY.open("a") as handle:
        handle.write(json.dumps(entry, sort_keys=True, default=str) + "\n")


def discover_session(competition: str) -> Path | None:
    candidates: list[tuple[float, Path]] = []
    projects = ARGUS_HOME / "projects"
    for session in projects.glob("s-*"):
        mission_view = session / "mission-view.json"
        if not mission_view.is_file():
            continue
        try:
            text = mission_view.read_text(errors="replace")
        except OSError:
            continue
        if competition in text:
            candidates.append((mission_view.stat().st_mtime, session))
    return max(candidates, default=(0.0, None))[1]


def latest_accepted_review(session: Path) -> dict[str, Any] | None:
    events = session / "events.jsonl"
    if not events.is_file():
        return None
    latest: dict[str, Any] | None = None
    for line in events.read_text(errors="replace").splitlines():
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        if (
            event.get("type") == "round.review.completed"
            and event.get("status") == "done"
            and not event.get("review_skipped", False)
        ):
            if latest is None or float(event.get("ts", 0)) > float(latest.get("ts", 0)):
                latest = event
    return latest


def sanitize_report(report: dict[str, Any]) -> dict[str, Any]:
    result = dict(report)
    result.pop("submission_path", None)
    return result


def feedback_markdown(competition: str, entries: list[dict[str, Any]]) -> str:
    lines = [
        "# Private leaderboard feedback",
        "",
        "Generated by the external MLE-Bench controller after independent Reviewer approval.",
        "Private labels and answer files remain inaccessible; only aggregate leaderboard feedback is exposed.",
        "",
    ]
    for entry in entries:
        report = entry.get("report") or {}
        lines.extend(
            [
                f"## Submission {entry['submission_number']}",
                "",
                f"- Submitted: `{entry['submitted_at']}`",
                f"- Reviewed: `{entry['reviewed_at']}`",
                f"- SHA256: `{entry['submission_sha256']}`",
                f"- Score: `{report.get('score')}`",
                f"- Valid submission: `{report.get('valid_submission')}`",
                f"- Lower is better: `{report.get('is_lower_better')}`",
                f"- Above median: `{report.get('above_median')}`",
                f"- Minimum completion gate (bronze or better): `{report.get('any_medal')}`",
                f"- Medal: gold=`{report.get('gold_medal')}`, silver=`{report.get('silver_medal')}`, bronze=`{report.get('bronze_medal')}`",
                f"- Thresholds: gold=`{report.get('gold_threshold')}`, silver=`{report.get('silver_threshold')}`, bronze=`{report.get('bronze_threshold')}`, median=`{report.get('median_threshold')}`",
                f"- Reviewer reason: {entry.get('review_reason', '').strip()}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def write_feedback(project: Path, competition: str, history: list[dict[str, Any]]) -> None:
    entries = [row for row in history if row.get("competition") == competition and row.get("report")]
    if not entries:
        return
    payload = {
        "schema_version": 1,
        "policy": "reviewer-approved-multiple-submissions-with-private-feedback",
        "competition": competition,
        "latest": entries[-1],
        "history": entries,
        "updated_at": time.time(),
    }
    atomic_json(project / "PRIVATE_LEADERBOARD_FEEDBACK.json", payload)
    latest_report = entries[-1].get("report") or {}
    atomic_json(
        project / "MLE_MEDAL_GATE.json",
        {
            "schema_version": 1,
            "competition": competition,
            "minimum": "bronze",
            "satisfied": bool(latest_report.get("any_medal")),
            "score": latest_report.get("score"),
            "is_lower_better": latest_report.get("is_lower_better"),
            "bronze_threshold": latest_report.get("bronze_threshold"),
            "submission_number": entries[-1].get("submission_number"),
            "submission_sha256": entries[-1].get("submission_sha256"),
            "updated_at": time.time(),
        },
    )
    md = project / "PRIVATE_LEADERBOARD_FEEDBACK.md"
    tmp = md.with_suffix(md.suffix + ".tmp")
    tmp.write_text(feedback_markdown(competition, entries))
    os.replace(tmp, md)


def notify_agent(project: Path, entry: dict[str, Any]) -> dict[str, Any]:
    report = entry.get("report") or {}
    message = (
        "Operator policy update: Reviewer-approved submissions may be graded multiple times. "
        f"Submission #{entry['submission_number']} received private leaderboard score "
        f"{report.get('score')} (above_median={report.get('above_median')}, "
        f"gold={report.get('gold_medal')}, silver={report.get('silver_medal')}, "
        f"bronze={report.get('bronze_medal')}, minimum_gate={report.get('any_medal')}). "
        "Read PRIVATE_LEADERBOARD_FEEDBACK.json and MLE_MEDAL_GATE.json. "
        "You may use this aggregate feedback for the next experiment, but private labels, "
        "answers, grader internals, and prepared/private remain forbidden. A new submission "
        "must again pass independent Reviewer approval. The project must not complete until "
        "MLE_MEDAL_GATE.json has satisfied=true (bronze or better)."
    )
    env = os.environ.copy()
    env["ARGUS_SKILL_HOME"] = str(ARGUS_HOME)
    env["ARGUS_SKILL_SOURCE_ROOT"] = CFG["ARGUS_REPO"]
    proc = subprocess.run(
        [ARGUS_BIN, "--project-root", str(project), "--notify", message],
        cwd=project,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    return {"exit_code": proc.returncode, "output": proc.stdout[-2000:]}


def grade_submission(
    competition: str,
    project: Path,
    submission: Path,
    digest: str,
    review: dict[str, Any],
    history: list[dict[str, Any]],
) -> dict[str, Any]:
    competition_history = [row for row in history if row.get("competition") == competition]
    number = len(competition_history) + 1
    submitted_at = utc_iso()
    stamp = submitted_at.replace(":", "").replace("-", "")
    submission_dir = GRADE_ROOT / competition / "submissions"
    submission_dir.mkdir(parents=True, exist_ok=True)
    snapshot = submission_dir / f"{number:03d}-{stamp}-{digest[:12]}.csv"
    tmp = snapshot.with_suffix(snapshot.suffix + ".tmp")
    shutil.copy2(submission, tmp)
    snapshot_digest = sha256_file(tmp)
    if snapshot_digest != digest:
        tmp.unlink(missing_ok=True)
        raise RuntimeError("submission changed while snapshotting")
    os.replace(tmp, snapshot)

    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = ""
    env["NVIDIA_VISIBLE_DEVICES"] = "void"
    env["ROCR_VISIBLE_DEVICES"] = ""
    proc = subprocess.run(
        [str(MLEBENCH_PYTHON), "-c", GRADE_SNIPPET, str(snapshot), competition, str(DATA_ROOT)],
        cwd=MLEBENCH_REPO,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    log_path = snapshot.with_suffix(".grade.log")
    log_path.write_text(proc.stdout)
    report: dict[str, Any] | None = None
    for line in reversed(proc.stdout.splitlines()):
        if line.startswith("__MLE_REPORT__"):
            report = sanitize_report(json.loads(line[len("__MLE_REPORT__") :]))
            break

    entry: dict[str, Any] = {
        "schema_version": 1,
        "competition": competition,
        "submission_number": number,
        "submission_sha256": digest,
        "snapshot": str(snapshot),
        "grade_log": str(log_path),
        "grade_exit_code": proc.returncode,
        "submitted_at": submitted_at,
        "reviewed_at": utc_iso(float(review.get("ts", 0))),
        "review_ts": float(review.get("ts", 0)),
        "review_reason": str(review.get("reason", "")),
        "report": report,
    }
    append_history(entry)
    history.append(entry)
    write_feedback(project, competition, history)
    if report is not None:
        entry["notification"] = notify_agent(project, entry)
    return entry


def process_competition(
    competition: str,
    stable_seconds: float,
    history: list[dict[str, Any]],
    state: dict[str, Any],
) -> dict[str, Any] | None:
    project = CAMPAIGN_ROOT / "projects" / competition
    submission = project / "submission.csv"
    if not submission.is_file() or submission.stat().st_size == 0:
        return None
    if not all((project / name).is_file() for name in ("RUN_MANIFEST.json", "RESULTS.md", "CHECKPOINT.md")):
        return None
    session = discover_session(competition)
    if session is None:
        return None
    review = latest_accepted_review(session)
    if review is None:
        return None
    stat = submission.stat()
    review_ts = float(review.get("ts", 0))
    # A submission written after the latest accepted review has not been approved yet.
    if stat.st_mtime > review_ts + 2.0:
        return None
    if time.time() - stat.st_mtime < stable_seconds:
        return None
    digest = sha256_file(submission)
    graded = {
        row.get("submission_sha256")
        for row in history
        if row.get("competition") == competition and row.get("report") is not None
    }
    if digest in graded:
        return None
    retry = state.setdefault("retry_after", {}).get(f"{competition}:{digest}", 0)
    if time.time() < float(retry):
        return None
    try:
        entry = grade_submission(competition, project, submission, digest, review, history)
    except Exception as exc:  # noqa: BLE001 - watcher must stay alive
        state.setdefault("errors", []).append(
            {"competition": competition, "submission_sha256": digest, "error": repr(exc), "at": time.time()}
        )
        state["retry_after"][f"{competition}:{digest}"] = time.time() + 300
        return None
    state.setdefault("last_submission", {})[competition] = {
        "sha256": digest,
        "submission_number": entry["submission_number"],
        "score": (entry.get("report") or {}).get("score"),
        "submitted_at": entry["submitted_at"],
    }
    return entry


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--poll-seconds", type=float, default=float(CFG.get("GRADE_POLL_SECONDS", "5")))
    parser.add_argument("--stable-seconds", type=float, default=float(CFG.get("GRADE_STABLE_SECONDS", "5")))
    parser.add_argument("--once", action="store_true")
    parser.add_argument("--competition", default="")
    args = parser.parse_args()

    GRADE_ROOT.mkdir(parents=True, exist_ok=True)
    lock_handle = LOCK.open("a+")
    try:
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        print("grade watcher already running", flush=True)
        return 0

    competitions = [line for line in COMPETITION_LIST.read_text().splitlines() if line]
    if args.competition:
        competitions = [args.competition]
    history = read_history()
    try:
        state = json.loads(STATE.read_text()) if STATE.exists() else {}
    except (OSError, json.JSONDecodeError):
        state = {}
    state.update({"pid": os.getpid(), "started_at": time.time(), "policy": "reviewer-approved"})
    for competition in competitions:
        project = CAMPAIGN_ROOT / "projects" / competition
        if project.is_dir():
            write_feedback(project, competition, history)
    atomic_json(STATE, state)

    while True:
        for competition in competitions:
            entry = process_competition(competition, args.stable_seconds, history, state)
            if entry is not None:
                report = entry.get("report") or {}
                print(
                    json.dumps(
                        {
                            "competition": competition,
                            "submission_number": entry["submission_number"],
                            "sha256": entry["submission_sha256"],
                            "score": report.get("score"),
                            "valid_submission": report.get("valid_submission"),
                            "above_median": report.get("above_median"),
                        },
                        sort_keys=True,
                    ),
                    flush=True,
                )
        state["updated_at"] = time.time()
        atomic_json(STATE, state)
        if args.once:
            break
        time.sleep(max(1.0, args.poll_seconds))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
