"""Entirely generated byte journals and SQLite receipts; no incident fixture."""

import json
import os
import sqlite3

import pytest

from argus.core.accounting_integrity import AccountingIntegrityError, strict_jsonl
from argus.core.incident_recovery import OfflineRecovery, digest, validate_recovered
from argus.core.usage import UsageRecord, summarize_usage, usage_recorded_event


def encoded(row):
    return json.dumps(row, sort_keys=True).encode() + b"\n"


@pytest.fixture(params=[("synthetic-alpha", 41, 0.25), ("synthetic-beta", 73, 0.75)])
def case(tmp_path, request):
    project, receipt_id, charge = request.param
    source = "/offline-source/projects/" + project  # identity only; never opened
    model = dict(
        session_id="known-session",
        model="synthetic-model",
        input_tokens=11,
        cached_input_tokens=2,
        cache_write_tokens=0,
        output_tokens=3,
        reasoning_output_tokens=0,
        total_nano_aiu=int(charge * 100_000_000_000),
        created_at="12",
        usage_event_id=receipt_id,
        cost_usd=charge,
    )
    known = UsageRecord.from_jsonable(
        dict(
            call_id="known-call",
            project_id=project,
            provider="copilot",
            model="synthetic-model",
            run_label="test",
            status="completed",
            started_at=10,
            completed_at=15,
            pricing_status="priced",
            cost_usd=charge,
            input_tokens=11,
            cached_input_tokens=2,
            cache_write_tokens=0,
            output_tokens=3,
            reasoning_output_tokens=0,
            total_nano_aiu=model["total_nano_aiu"],
            model_usage=[model],
        )
    )
    reservation = dict(
        id="legacy-reservation",
        call_id="unknown-call",
        project_id=project,
        project_root=source,
        provider="copilot",
        model="synthetic-model",
        run_label="test",
        created_at=10,
        pid=4242,
        amount_usd=2.0,
        observed_cost_usd=0.125,
        observed_tokens=9,
    )
    ack = dict(project_id=project, liability_usd=3, reason="Synthetic existing approval")
    state = dict(
        version=3,
        day="2000-01-01",
        updated_at=20,
        project_roots=[source],
        reservations=[reservation],
        unresolved=[],
        acknowledgements={"older-call": ack},
    )
    prefix = b'{"call_id":"unknown-call","error":"truncated'
    usage = prefix + encoded(known.to_jsonable())
    part1 = b'{"type":"provider.request.completed","call_id":"known-call","error":"broken'
    part2 = b'{"type":"life.planner.start","partial":'
    events = part1 + encoded(usage_recorded_event(known))
    second_offset = len(events)
    events += part2 + encoded(dict(type="synthetic.retained", ts=11))
    events += encoded(
        dict(
            type="provider.request.started",
            call_id="unknown-call",
            provider="copilot",
            run_label="test",
            ts=11,
        )
    )
    events += encoded(
        dict(
            type="budget.reservation.created",
            reservation_id="legacy-reservation",
            call_id="unknown-call",
            provider="copilot",
            model="synthetic-model",
            amount_usd=2.0,
            run_label="test",
            ts=10,
        )
    )
    events += encoded(
        dict(
            type="agent.io.complete",
            call_id="unknown-call",
            turn_failed=True,
            thread_id="unknown-session",
            backend="copilot",
            model="synthetic-model",
            run_label="test",
            ts=14,
        )
    )
    originals = {
        "cost-control.json": encoded(state),
        "cost-control.jsonl": encoded({"type": "synthetic.audit"}),
        "config.json": encoded({"synthetic": True}),
        f"projects/{project}/usage.jsonl": usage,
        f"projects/{project}/events.jsonl": events,
    }
    db = tmp_path / "generated.sqlite"
    with sqlite3.connect(db) as con:
        con.execute(
            "CREATE TABLE assistant_usage_events (id INTEGER PRIMARY KEY, session_id TEXT, model TEXT, input_tokens INTEGER, cache_read_tokens INTEGER, cache_write_tokens INTEGER, output_tokens INTEGER, reasoning_tokens INTEGER, total_nano_aiu INTEGER, created_at TEXT)"
        )
        con.execute(
            "INSERT INTO assistant_usage_events VALUES (?,?,?,?,?,?,?,?,?,?)",
            (
                receipt_id,
                "known-session",
                "synthetic-model",
                11,
                2,
                0,
                3,
                0,
                model["total_nano_aiu"],
                12,
            ),
        )
    db_bytes = db.read_bytes()

    def cut(offset, data):
        return dict(offset=offset, length=len(data), sha256=digest(data))

    spec = dict(
        version=1,
        project_id=project,
        source_project_root=source,
        reservation_id="legacy-reservation",
        known_call_id="known-call",
        unknown_session_id="unknown-session",
        originals={name: digest(raw) for name, raw in originals.items()},
        usage_cuts=[cut(0, prefix)],
        event_cuts=[cut(0, part1), cut(second_offset, part2)],
        provider_evidence=dict(
            sqlite_sha256=digest(db_bytes), ids=[receipt_id], nano_aiu=model["total_nano_aiu"]
        ),
    )
    parent = tmp_path / "private"
    parent.mkdir(mode=0o700)
    with OfflineRecovery.create(parent, originals, db_bytes) as work:
        yield work, spec, state, originals, charge


def ready(work, spec):
    manifest = work.prepare(spec)
    result = work.apply_to_copy(
        manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"]
    )
    assert result["phase"] == "committed"
    return manifest


def assert_projection(work, spec, state, originals, charge):
    actual = work.read_state()
    assert actual["day"] == state["day"]
    assert actual["updated_at"] == state["updated_at"]
    assert actual["acknowledgements"] == state["acknowledgements"]
    assert actual["reservations"] == []
    assert len(actual["unresolved"]) == 1
    unknown = actual["unresolved"][0]
    assert unknown["call_id"] == "unknown-call" and unknown["pricing_status"] == "unknown"
    for key in ("observed_cost_usd", "observed_tokens", "created_at", "amount_usd", "project_root"):
        assert unknown[key] == state["reservations"][0][key]
    rows = strict_jsonl(
        work.root / f"projects/{spec['project_id']}/usage.jsonl", require_call_id=True
    )
    assert len(rows) == 1 and rows[0]["call_id"] == "known-call" and rows[0]["cost_usd"] == charge
    # Money is folded from the actual canonical ledger, not event count.
    summary = summarize_usage([UsageRecord.from_jsonable(r) for r in rows])
    assert summary.cost_usd == charge
    intent = json.loads(next((work.root / "cost-finalizers").glob("*.json")).read_bytes())
    validate_recovered(work.root, intent, unknown)
    archive = work.root / "accounting-recoveries" / unknown["recovery_provenance"]
    for name, raw in originals.items():
        assert (archive / "original" / name).read_bytes() == raw


def test_exact_charge_once_unknown_and_current_ack_preserved(case):
    work, spec, state, originals, charge = case
    manifest = ready(work, spec)
    assert_projection(*case)
    # Simulate a later supported approval in the private laboratory only.
    current = work.read_state()
    current["acknowledgements"]["unknown-call"] = dict(
        project_id=spec["project_id"], liability_usd=4, reason="Synthetic later review"
    )
    (work.root / "cost-control.json").write_bytes(encoded(current))
    before = (work.root / "cost-control.json").read_bytes()
    result = work.apply_to_copy(
        manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"]
    )
    assert result["duplicate"] is True
    assert (work.root / "cost-control.json").read_bytes() == before
    assert current["unresolved"][0]["pricing_status"] == "unknown"


@pytest.mark.parametrize(
    "point",
    [
        "before_projection",
        "usage",
        "events",
        "intent",
        "after:cost-control.json",
        "after_projection",
    ],
)
def test_durable_crash_boundaries_resume(case, point):
    work, spec, *_ = case
    manifest = work.prepare(spec)
    if point in {"usage", "events"}:
        point = f"after:projects/{spec['project_id']}/{point}.jsonl"
    if point == "intent":
        point = "after:" + next(n for n in manifest["order"] if n.startswith("cost-finalizers/"))

    def crash(stage):
        if stage == point:
            raise OSError("synthetic interruption")

    with pytest.raises(OSError, match="synthetic"):
        work.apply_to_copy(
            manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"], fault=crash
        )
    with pytest.raises(AccountingIntegrityError):
        work.read_state()
    work.apply_to_copy(manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"])
    assert_projection(*case)


@pytest.mark.parametrize(
    "field,value",
    [
        ("version", 2),
        ("version", True),
        ("extra", 0),
        ("project_id", "../escape"),
        ("source_project_root", "relative"),
    ],
)
def test_spec_rejected_before_archive(case, field, value):
    work, spec, *_ = case
    spec[field] = value
    with pytest.raises(ValueError):
        work.prepare(spec)
    assert not (work.root / "accounting-recoveries").exists()


@pytest.mark.parametrize(
    "which", ["config.json", "cost-control.json", "cost-control.jsonl", "usage", "events"]
)
def test_source_cas_before_marker(case, which):
    work, spec, *_ = case
    manifest = work.prepare(spec)
    if which in {"usage", "events"}:
        which = f"projects/{spec['project_id']}/{which}.jsonl"
    target = work.root / which
    target.write_bytes(target.read_bytes() + b" ")
    before = target.read_bytes()
    with pytest.raises(ValueError, match="source changed"):
        work.apply_to_copy(manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"])
    assert target.read_bytes() == before
    assert not (work.root / "accounting-recovery.json").exists()


@pytest.mark.parametrize("name", ["config.json", "projects", "provider.db"])
def test_prepare_nofollow(case, tmp_path, name):
    work, spec, *_ = case
    target = work.root / name
    outside = tmp_path / "outside"
    target.rename(outside)
    target.symlink_to(outside, target_is_directory=outside.is_dir())
    with pytest.raises((ValueError, OSError)):
        work.prepare(spec)
    assert not (work.root / "accounting-recoveries").exists()


@pytest.mark.parametrize("name", ["config.json", "projects", "cost-control.lock"])
def test_apply_nofollow(case, tmp_path, name):
    work, spec, *_ = case
    manifest = work.prepare(spec)
    target = work.root / name
    outside = tmp_path / "outside"
    if target.exists():
        target.rename(outside)
    else:
        outside.write_bytes(b"untouched")
    target.symlink_to(outside, target_is_directory=outside.is_dir())
    before = (
        {str(p): p.read_bytes() for p in outside.rglob("*") if p.is_file()}
        if outside.is_dir()
        else outside.read_bytes()
    )
    with pytest.raises((ValueError, OSError)):
        work.apply_to_copy(manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"])
    after = (
        {str(p): p.read_bytes() for p in outside.rglob("*") if p.is_file()}
        if outside.is_dir()
        else outside.read_bytes()
    )
    assert after == before
    assert not (work.root / "accounting-recovery.json").exists()


def test_closed_capability_no_existing_root_api(case):
    work, spec, *_ = case
    work.close()
    with pytest.raises(ValueError, match="closed"):
        work.prepare(spec)
    with pytest.raises(TypeError):
        OfflineRecovery()


def test_reject_shared_parent(tmp_path):
    parent = tmp_path / "shared"
    parent.mkdir(mode=0o755)
    with pytest.raises(ValueError, match="private"):
        OfflineRecovery.create(parent, {"config.json": b"{}"}, b"sqlite")
    assert list(parent.iterdir()) == []


@pytest.mark.parametrize("field", ["ids", "nano_aiu", "sqlite_sha256"])
def test_provider_corroboration_before_mutation(case, field):
    work, spec, *_ = case
    spec["provider_evidence"][field] = {"ids": [999], "nano_aiu": 1, "sqlite_sha256": "a" * 64}[
        field
    ]
    with pytest.raises(ValueError):
        work.prepare(spec)
    assert not (work.root / "accounting-recoveries").exists()


def test_projection_tamper_rejected(case):
    work, spec, *_ = case
    manifest = work.prepare(spec)
    target = work.root / "accounting-recoveries" / manifest["id"] / "projection/cost-control.json"
    target.write_bytes(target.read_bytes() + b" ")
    with pytest.raises(ValueError, match="projection changed"):
        work.apply_to_copy(manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"])
    assert not (work.root / "accounting-recovery.json").exists()


def snapshot(root):
    return {
        str(p.relative_to(root)): ("symlink", os.readlink(p))
        if p.is_symlink()
        else ("file", p.read_bytes())
        for p in root.rglob("*")
        if p.is_symlink() or p.is_file()
    }


@pytest.mark.parametrize("partial", [False, True])
@pytest.mark.parametrize(
    "target",
    [
        "project",
        "finalizers",
        "archive",
        "original",
        "projection",
        "segments",
        "manifest",
        "provider",
        "audit",
        "marker",
    ],
)
def test_all_archive_and_destination_rebinding_before_mutation(case, partial, target, tmp_path):
    work, spec, *_ = case
    manifest = work.prepare(spec)

    def run(**kw):
        return work.apply_to_copy(
            manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"], **kw
        )

    if partial:

        def interrupt(stage):
            if stage == "before_projection":
                raise OSError("synthetic interruption")

        with pytest.raises(OSError):
            run(fault=interrupt)
    archive = work.root / "accounting-recoveries" / manifest["id"]
    targets = {
        "project": work.root / "projects" / spec["project_id"],
        "finalizers": work.root / "cost-finalizers",
        "archive": archive,
        "original": archive / "original",
        "projection": archive / "projection",
        "segments": archive / "segments",
        "manifest": archive / "manifest.json",
        "provider": archive / "provider-evidence.db",
        "audit": archive / "audit.jsonl",
        "marker": work.root / "accounting-recovery.json",
    }
    path = targets[target]
    outside = tmp_path / "unrelated"
    if path.exists():
        path.rename(outside)
    elif target == "finalizers":
        outside.mkdir()
    else:
        outside.write_bytes(b"unrelated")
    path.symlink_to(outside, target_is_directory=outside.is_dir())
    before = snapshot(tmp_path)
    with pytest.raises((ValueError, OSError)):
        run()
    assert snapshot(tmp_path) == before


def test_resume_after_process_death(case):
    # Real child exit after a durable pending write; no runtime/provider started.
    work, spec, *_ = case
    manifest = work.prepare(spec)
    parent, name, token = work.root.parent, work.root.name, work.resume_token
    work.close()
    pid = os.fork()
    if pid == 0:
        with OfflineRecovery.resume(parent, name, resume_token=token) as child:

            def crash(stage):
                if stage == "after:cost-control.json":
                    os._exit(23)

            child.apply_to_copy(
                manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"], fault=crash
            )
        os._exit(24)
    _, status = os.waitpid(pid, 0)
    assert os.waitstatus_to_exitcode(status) == 23
    with OfflineRecovery.resume(parent, name, resume_token=token) as reopened:
        with pytest.raises(AccountingIntegrityError):
            reopened.read_state()
        reopened.apply_to_copy(manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"])
        assert_projection(reopened, *case[1:])


def test_wrong_resume_identity_rejected(case):
    work, *_ = case
    parent, name = work.root.parent, work.root.name
    work.close()
    before = snapshot(parent)
    with pytest.raises(ValueError, match="ownership"):
        OfflineRecovery.resume(parent, name, resume_token="incorrect")
    assert snapshot(parent) == before


def test_copy_lock_excludes_cooperating_reopen(case):
    from argus.core.cost_control import CostControlLockBusyError

    work, *_ = case
    with pytest.raises(CostControlLockBusyError):
        OfflineRecovery.resume(work.root.parent, work.root.name, resume_token=work.resume_token)


def test_late_directory_swap_cannot_redirect_replace(case, tmp_path, monkeypatch):
    import shutil

    work, spec, *_ = case
    manifest = work.prepare(spec)
    project = work.root / "projects" / spec["project_id"]
    outside, moved = tmp_path / "outside-copy", tmp_path / "moved-copy"
    shutil.copytree(project, outside)
    before = snapshot(outside)
    replace = os.replace

    def swapped(src, dst, **kwargs):
        if dst == "usage.jsonl" and not moved.exists():
            project.rename(moved)
            project.symlink_to(outside, target_is_directory=True)
        return replace(src, dst, **kwargs)

    monkeypatch.setattr(os, "replace", swapped)
    with pytest.raises((ValueError, OSError)):
        work.apply_to_copy(manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"])
    assert snapshot(outside) == before
    assert json.loads((work.root / "accounting-recovery.json").read_bytes())["phase"] == "pending"


def test_input_cannot_replace_ownership_lock(tmp_path):
    private = tmp_path / "private"
    private.mkdir(mode=0o700)
    with pytest.raises(ValueError):
        OfflineRecovery.create(private, {"offline-copy.lock": b"replacement"}, b"db")
    assert list(private.iterdir()) == []


@pytest.mark.parametrize("phase", ["unexpected", None, False])
def test_unknown_marker_never_authorizes_resume(case, phase):
    work, spec, *_ = case
    manifest = work.prepare(spec)
    (work.root / "accounting-recovery.json").write_bytes(
        encoded(dict(id=manifest["id"], manifest_sha256=manifest["manifest_sha256"], phase=phase))
    )
    before = snapshot(work.root)
    with pytest.raises(ValueError, match="modified recovery"):
        work.apply_to_copy(manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"])
    assert snapshot(work.root) == before


def test_unknown_manifest_fields_rejected_even_with_matching_hash(case):
    work, spec, *_ = case
    manifest = work.prepare(spec)
    target = work.root / "accounting-recoveries" / manifest["id"] / "manifest.json"
    modified = json.loads(target.read_bytes())
    modified["extra"] = True
    target.write_bytes(encoded(modified))
    before = snapshot(work.root)
    with pytest.raises(ValueError, match="bounded recovery manifest"):
        work.apply_to_copy(manifest["id"], expected_manifest_sha256=digest(target.read_bytes()))
    assert snapshot(work.root) == before


def test_archived_spec_is_transaction_bound(case):
    work, spec, *_ = case
    manifest = work.prepare(spec)
    target = work.root / "accounting-recoveries" / manifest["id"] / "spec.json"
    changed = json.loads(target.read_bytes())
    changed["unknown_session_id"] = "other-session"
    target.write_bytes(encoded(changed))
    before = snapshot(work.root)
    with pytest.raises(ValueError, match="specification identity"):
        work.apply_to_copy(manifest["id"], expected_manifest_sha256=manifest["manifest_sha256"])
    assert snapshot(work.root) == before
