/** Ship the same extension in Python wheels without requiring a Node build. */
import { readFileSync, writeFileSync } from 'node:fs';
import ts from 'typescript';

const source = new URL('../src/piOutputSchemaExtension.ts', import.meta.url);
const output = new URL('../../../argus/agent_cli/pi_output_schema_extension.mjs', import.meta.url);
const generated = '// Generated by packages/runtime/scripts/generatePiExtension.ts. Do not edit.\n'
  + ts.transpileModule(readFileSync(source, 'utf8'), {
    compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022, newLine: ts.NewLineKind.LineFeed },
  }).outputText;
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== generated) {
    throw new Error('Pi output schema extension is stale; run npm run runtime:generate');
  }
} else writeFileSync(output, generated);
