"""Create a clean-slate EMNLP auto-research project from the AGENTS template."""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from importlib import resources
from pathlib import Path

from ..skills.builtins import (
    AVAILABLE_DOMAINS,
    DEFAULT_PROJECT_BUILTIN_SKILLS_DIR,
    DOMAIN_DESCRIPTIONS,
    builtin_skill_source_path,
    iter_builtin_skill_texts,
    seed_builtin_skills,
    seed_builtin_skills_for_domain,
)

DEFAULT_PARENT = Path(os.environ.get("ARGUS_SKILL_PROJECT_PARENT", str(Path.home())))
DEFAULT_PREFIX = "agent-emnlp-auto-research-v"
DEFAULT_TEMPLATE = "agent-md-new-project-template.md"
DEFAULT_PROJECT_CODE_DIR = "code"
PYTHON = Path(os.environ.get("ARGUS_SKILL_PYTHON", sys.executable))
COPY_READY_HEADING = "## Copy-ready `AGENTS.md`"
TRAILER = "Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>"
HARNESS_DECLARATION_HEADING = "## Argus harness modification map"
HARNESS_ARCHITECTURE_DECLARATION = f"""
{HARNESS_DECLARATION_HEADING}
This workspace is an EMNLP auto-research project generated by the Argus
agent harness. Treat `AGENTS.md`, `research/`, `experiments/`, and `paper/`
as project artifacts. Treat the active `argus_skill` package/source checkout
as the harness that drives the project. Do not mix the two when making fixes.

Runtime route:

```text
argus-skill / python -m argus_skill
  -> argus_skill/apps/cli.py
  -> argus_skill/apps/_runtime.py or argus_skill/daemon/life_worker.py
  -> argus_skill/life/supervisor.py
  -> _SkillLoopRunner.execute(...)
  -> argus_skill/loop.py
  -> argus_skill/engineer/runner.py
  -> argus_skill/reviewer/_core.py
```

Ownership map:

| Concern | Edit here in the Argus source checkout |
| --- | --- |
| CLI flags, REPL, daemon start/stop, status/follow/watch | `argus_skill/apps/cli.py`, `argus_skill/manager/repl.py`, `argus_skill/apps/_runtime.py`, `argus_skill/daemon/life_worker.py`, `argus_skill/apps/_watch.py` |
| One mission's skill matcher -> distiller -> engineer -> reviewer flow | `argus_skill/loop.py` |
| L1 engineer retries, checks, session carryover, watchdogs, backend failures | `argus_skill/engineer/runner.py`, `argus_skill/engineer/checks.py` |
| L2 reviewer verdicts, JSON schema, reviewer-to-engineer next action | `argus_skill/reviewer/_core.py`, `argus_skill/reviewer/reviewer_schema.json` |
| L4 planner continuous-mode task creation and mission supervision | `argus_skill/life/supervisor.py`, `argus_skill/planner/planner.py` |
| Skill distillation/compaction and distilled-skill storage, writeback, builtin skill seeding | `argus_skill/scientist/*` (distiller/compactor), `argus_skill/skills/store.py`, `argus_skill/skills/builtins.py`, `argus_skill/builtin_skills/` |
| EMNLP artifact-validation helpers (importable checks, no completion gating) | `argus_skill/skills/pipeline_contracts.py`, `argus_skill/skills/pipeline_policy.py` |
| Final-submission completion certification (L2 reviewer contract + checklist) | `argus_skill/reviewer/_core.py`, `argus_skill/reviewer/reviewer_schema.json` |
| Academic-language, infrastructure-leak, and visual-layout review tools | `argus_skill/skills/academic_language_review.py`, `argus_skill/skills/paper_infrastructure_review.py`, `argus_skill/skills/paper_layout_review.py` |
| Image-2 paper figure prompt/generation/review/metadata helpers | `argus_skill/tools/image_tool.py` |
| New auto-research project launcher and this declaration | `argus_skill/tools/new_auto_research_project.py` |

Modification rule: final-submission completion is certified by the L2 reviewer
contract — to change what "done" requires, edit the reviewer prompt/checklist in
`argus_skill/reviewer/_core.py` and `reviewer_schema.json`; if an artifact
check should be stricter or looser, change `pipeline_contracts.py`; if an agent
needs different instructions while executing paper work, change the relevant
`argus_skill/builtin_skills/*.md` or `SkillLoop._build_engineer_prompt`. Do not
hand-edit generated review JSON, manifest/freshness records, or
submission-assurance artifacts just to make completion look certified.
""".strip()

STARTER_CODE_TEMPLATE_PACKAGE = "argus_skill.tools.project_templates.code"
STARTER_CODE_TEMPLATE_FILES = (
    "__init__.py",
    "llm.py",
    "gpu_env.py",
    "experiment_io.py",
    "run_experiments.py",
    "generate_image_2.py",
    "generate_image2_figure.py",
)


class LaunchError(RuntimeError):
    """Raised when project bootstrapping cannot safely continue."""


@dataclass(frozen=True)
class LaunchConfig:
    parent: Path = DEFAULT_PARENT
    version: str | None = None
    project_dir: Path | None = None
    template_path: Path | None = None
    objective: str | None = None
    non_goals: str | None = None
    compute_budget: str | None = None
    domain: str | None = None  # e.g. "cv", "multimodal", "agent", "infra"
    venue: str = "EMNLP"  # target publication venue: "EMNLP" | "AAAI"
    start_daemon: bool = True
    init_git: bool = True
    dry_run: bool = False
    overwrite_empty: bool = True
    create_project_venv: bool = True


@dataclass(frozen=True)
class LaunchResult:
    project_dir: Path
    agents_path: Path
    skills_dir: Path
    project_name: str
    version: str
    domain: str | None
    daemon_started: bool
    git_commit: str | None
    daemon_output: str
    status_output: str
    project_venv: Path | None = None
    dry_run: bool = False


def extract_copy_ready_agents_md(template_text: str) -> str:
    """Return the copy-ready AGENTS.md body from a built-in template.

    The body is wrapped in a fenced block under ``COPY_READY_HEADING`` and may
    itself contain nested code fences (e.g. ```python examples). To avoid
    closing the block at the first nested fence — which silently truncates the
    generated agent prompt — the wrapper uses a longer fence (four backticks)
    and we close only on a fence of at least the opening length with nothing but
    whitespace after it (CommonMark-style). This keeps any inner 3-backtick
    blocks as ordinary body content.
    """
    heading_index = template_text.find(COPY_READY_HEADING)
    if heading_index < 0:
        raise LaunchError(f"template is missing {COPY_READY_HEADING!r}")
    lines = template_text[heading_index:].split("\n")
    open_re = re.compile(r"^[ \t]{0,3}(`{3,})\s*([^`]*)$")
    fence_marker = None
    body_lines: list[str] = []
    open_index = None
    for index, line in enumerate(lines[1:], start=1):
        match = open_re.match(line)
        if match:
            fence_marker = match.group(1)
            open_index = index
            break
    if fence_marker is None or open_index is None:
        raise LaunchError("template is missing the opening markdown fence")
    close_re = re.compile(r"^[ \t]{0,3}`{" + str(len(fence_marker)) + r",}\s*$")
    closed = False
    for line in lines[open_index + 1:]:
        if close_re.match(line):
            closed = True
            break
        body_lines.append(line)
    if not closed:
        raise LaunchError("template is missing the closing markdown fence")
    body = "\n".join(body_lines).strip()
    if not body.startswith("# AGENTS.md"):
        raise LaunchError("copy-ready template body must start with '# AGENTS.md'")
    return body + "\n"


def render_agents_md(
    template_text: str,
    *,
    project_name: str,
    version: str,
    objective: str | None = None,
    non_goals: str | None = None,
    compute_budget: str | None = None,
) -> str:
    """Fill the project-specific fields in the copy-ready AGENTS.md template."""
    body = extract_copy_ready_agents_md(template_text)
    objective = objective or default_objective(project_name)
    non_goals = non_goals or default_non_goals(project_name, version)
    compute_budget = compute_budget or default_compute_budget()
    replacements = {
        "[write the target research problem and deliverable]": objective,
        "[write what must not be optimized, copied, or claimed]": non_goals,
        "[write limits and stop conditions]": compute_budget,
        "| [input] | [source] | [status] | [allowed use] | [rationale] |": (
            default_allowed_inputs_table_rows()
        ),
    }
    for old, new in replacements.items():
        body = body.replace(old, new)
    body = append_harness_architecture_declaration(body)
    unresolved = [
        token
        for token in (
            "[write the target research problem and deliverable]",
            "[write what must not be optimized, copied, or claimed]",
            "[write limits and stop conditions]",
            "| [input] | [source] | [status] | [allowed use] | [rationale] |",
        )
        if token in body
    ]
    if unresolved:
        raise LaunchError(f"rendered AGENTS.md still has placeholders: {unresolved}")
    return body


def append_harness_architecture_declaration(body: str) -> str:
    """Append the Argus harness modification map to generated AGENTS.md."""
    text = body.rstrip()
    if HARNESS_DECLARATION_HEADING in text:
        return text + "\n"
    return f"{text}\n\n{HARNESS_ARCHITECTURE_DECLARATION}\n"


def default_objective(project_name: str) -> str:
    return (
        f"Start {project_name} as a clean-slate EMNLP/ACL long-paper auto-research "
        "workspace: choose an independent frontier-domain thesis from current "
        "research, train or adapt a meaningful domain model with "
        "the available GPU budget, evaluate only on existing real benchmark sources "
        "or official task/data releases, run the full-scale evidence matrix, then write "
        "an exemplar-locked, visually polished EMNLP/ACL long-paper submission package "
        "that the L2 reviewer certifies `done` against the full pipeline checklist."
    )


def default_non_goals(project_name: str, version: str) -> str:
    return (
        f"Do not copy, rename, polish, or continue any prior `agent-emnlp-auto-research-v*` "
        f"workspace as {project_name}. Do not reuse prior titles, claims, benchmark "
        "episodes, results, figures, paper generators, review JSON, or paper story unless "
        "listed as allowed raw evidence with license/access status and a narrow rationale."
    )


def _gpu_budget_from_vault() -> str:
    """Render a GPU-allocation clause from the capability vault if available.

    Reads ``~/.argus-skill/capabilities/gpu_resources.json`` via
    :func:`argus_skill.tools.capability_vault.load_gpu_resources` so the
    generated ``AGENTS.md`` automatically reflects the operator's GPU grant
    without forcing the user to retype it on every project.
    """
    try:
        from .capability_vault import load_gpu_resources  # local import to avoid cycle
    except Exception:  # pragma: no cover - defensive
        return ""
    config = load_gpu_resources() or {}
    cuda_vis = str(config.get("cuda_visible_devices") or "").strip()
    if not cuda_vis:
        return ""
    devices = config.get("allowed_devices") or []
    max_mem = config.get("max_gpu_memory_gb")
    parts = [
        f"GPU allocation (from capability vault): ONLY CUDA devices [{cuda_vis}] are available; "
        f"every training/eval/inference command MUST run with CUDA_VISIBLE_DEVICES={cuda_vis} "
        "and MUST NOT touch any other device on the host."
    ]
    if devices:
        parts.append(f"Allowed device indices: {list(devices)}.")
    if max_mem:
        parts.append(f"Aggregate GPU memory budget: ~{max_mem} GB across the allocation.")
    return " ".join(parts)


def _project_venv_clause() -> str:
    """Tell the agent where the project's own virtualenv lives.

    The launcher creates `<project>/.venv` so the agent can pip install
    experiment dependencies without touching the Argus framework venv.
    Without this clause the agent often `pip install`s into whatever
    Python first appears on PATH (which is the Argus venv) and ends up
    polluting the harness with project-specific packages.
    """

    return (
        "Project Python environment: this workspace ships with its own isolated "
        "`./.venv` (created by the launcher). Use `./.venv/bin/python` and "
        "`./.venv/bin/pip` for ALL experiment / dataset / training / inference "
        "code and for any `pip install` of project dependencies. NEVER `pip install` "
        "into the Argus framework Python (the interpreter that runs "
        "`python -m argus_skill.*` / `${ARGUS_SKILL_PYTHON}`) — that interpreter is "
        "reserved exclusively for the argus-skill daemon, reviewer, and helper CLIs. "
        "If a needed package is missing inside `./.venv`, run "
        "`./.venv/bin/pip install <pkg>` from the project root; do not fall back "
        "to system pip or the framework venv."
    )


def default_compute_budget() -> str:
    base = (
        "Use API/model budget only for necessary literature, coding, image-2, review, and "
        "experiment work. Use local GPU capacity for the strongest feasible "
        "domain-appropriate training/adaptation run rather than defaulting to tiny "
        "custom scorers. Stop or ask for operator guidance if a required real benchmark, "
        "model weight/license, GPU capability, or full-scale run is unavailable, or if "
        "repeated repair cycles make no review-relevant progress."
    )
    gpu_clause = _gpu_budget_from_vault()
    venv_clause = _project_venv_clause()
    parts = [p for p in (gpu_clause, venv_clause, base) if p]
    return "\n\n".join(parts)


def default_allowed_inputs_table_rows() -> str:
    return "\n".join(
        [
            "| Operator research playbook | provided by the launcher/operator when available | local operator guidance | Paper-quality and research-process guidance only | Stable cross-project writing and review policy |",
            "| Active Argus package/source checkout | active Python package plus `ARGUS_SKILL_SOURCE_ROOT` when set | local source/package | Reviewer, built-in skills, helper APIs, and daemon runtime | Required toolchain for this workspace without hard-coded host paths |",
            "| Exported built-in skills | `./argus_builtin_skills/*.md`, `./argus_builtin_skills/**/*.md` | generated local copy | Read-only local skill guidance | Keeps the daemon self-contained without copying the whole Argus repository |",
            "| Public literature, datasets, and repositories | verified URLs/scholarly sources | source-specific license/access | Topic discovery, citations, benchmark construction, and baseline implementation | Must be recorded before use in research artifacts |",
        ]
    )


def load_template_text(template_path: Path | None = None) -> str:
    if template_path is not None:
        return template_path.read_text(encoding="utf-8")
    source_path = builtin_skill_source_path() / DEFAULT_TEMPLATE
    if source_path.exists():
        return source_path.read_text(encoding="utf-8")
    for filename, text in iter_builtin_skill_texts():
        if filename == DEFAULT_TEMPLATE:
            return text
    raise LaunchError(f"built-in template not found: {DEFAULT_TEMPLATE}")


def normalize_version(raw: str | None) -> str:
    if raw is None:
        raise LaunchError("version is required when project_dir is not provided")
    value = raw.strip()
    match = re.fullmatch(r"(?:v)?(\d+)", value)
    if not match:
        match = re.fullmatch(rf"{re.escape(DEFAULT_PREFIX)}(\d+)", value)
    if not match:
        raise LaunchError(f"version must look like '15', 'v15', or '{DEFAULT_PREFIX}15': {raw!r}")
    return f"v{int(match.group(1))}"


def next_version(parent: Path, *, prefix: str = DEFAULT_PREFIX) -> str:
    max_seen = 0
    if parent.exists():
        for child in parent.iterdir():
            if not child.is_dir() or not child.name.startswith(prefix):
                continue
            suffix = child.name[len(prefix):]
            if suffix.isdigit():
                max_seen = max(max_seen, int(suffix))
    return f"v{max_seen + 1}"


def resolve_project(config: LaunchConfig) -> tuple[Path, str, str]:
    parent = config.parent.expanduser().resolve()
    if config.project_dir is not None:
        project_dir = config.project_dir.expanduser().resolve()
        name = project_dir.name
        match = re.fullmatch(rf"{re.escape(DEFAULT_PREFIX)}(\d+)", name)
        version = f"v{int(match.group(1))}" if match else normalize_version(config.version or "1")
        return project_dir, name, version
    version = normalize_version(config.version) if config.version else next_version(parent)
    name = f"{DEFAULT_PREFIX}{version.removeprefix('v')}"
    return parent / name, name, version


def create_project(config: LaunchConfig) -> LaunchResult:
    project_dir, project_name, version = resolve_project(config)
    agents_path = project_dir / "AGENTS.md"
    skills_dir = project_dir / DEFAULT_PROJECT_BUILTIN_SKILLS_DIR
    template_text = load_template_text(config.template_path)
    agents_md = render_agents_md(
        template_text,
        project_name=project_name,
        version=version,
        objective=config.objective,
        non_goals=config.non_goals,
        compute_budget=config.compute_budget,
    )
    if config.dry_run:
        return LaunchResult(
            project_dir=project_dir,
            agents_path=agents_path,
            skills_dir=skills_dir,
            project_name=project_name,
            version=version,
            domain=config.domain,
            daemon_started=False,
            git_commit=None,
            daemon_output="",
            status_output="",
            project_venv=None,
            dry_run=True,
        )
    _prepare_project_dir(project_dir, overwrite_empty=config.overwrite_empty)
    agents_path.write_text(agents_md, encoding="utf-8")
    if config.domain:
        seed_builtin_skills_for_domain(skills_dir, config.domain, overwrite=True)
    else:
        seed_builtin_skills(skills_dir, overwrite=True)
    seed_starter_code(project_dir, overwrite=True)
    seed_research_bootstrap(
        project_dir,
        project_name=project_name,
        objective=_continuous_objective_from_agents(agents_md),
        venue=config.venue,
        overwrite=True,
    )
    project_venv: Path | None = None
    if config.create_project_venv:
        try:
            project_venv = init_project_venv(project_dir)
        except (LaunchError, OSError, subprocess.TimeoutExpired) as exc:
            # The launcher should not die just because the project venv
            # bootstrap is slow/flaky; the user can rerun it manually.
            print(
                "argus-skill: warning: per-project .venv bootstrap failed "
                f"({exc!s}). Run `python -m venv .venv` inside the project "
                "directory and continue manually.",
                file=sys.stderr,
            )
    git_commit = init_git(project_dir, project_name) if config.init_git else None
    daemon_output = ""
    status_output = ""
    daemon_started = False
    if config.start_daemon:
        try:
            daemon_output = start_daemon(project_dir, agents_md)
            status_output = status(project_dir)
            daemon_started = True
        except LaunchError as exc:
            # Most likely the lifetime entry gate (missing operator special
            # prompt): the project is fully created, only the auto-start is
            # deferred until the operator configures their house rules.
            daemon_output = (
                "daemon NOT auto-started — finish the operator setup, then run "
                "`argus-skill --daemon --continuous --objective \"...\"` yourself.\n"
                f"{exc}"
            )
    return LaunchResult(
        project_dir=project_dir,
        agents_path=agents_path,
        skills_dir=skills_dir,
        project_name=project_name,
        version=version,
        domain=config.domain,
        daemon_started=daemon_started,
        git_commit=git_commit,
        daemon_output=daemon_output,
        status_output=status_output,
        project_venv=project_venv,
    )


def _prepare_project_dir(project_dir: Path, *, overwrite_empty: bool) -> None:
    if project_dir.exists():
        if not project_dir.is_dir():
            raise LaunchError(f"project path exists but is not a directory: {project_dir}")
        if any(project_dir.iterdir()):
            raise LaunchError(
                f"project directory is not empty: {project_dir}. "
                "Use a new version/path; this launcher never deletes existing work."
            )
        if not overwrite_empty:
            raise LaunchError(f"project directory already exists: {project_dir}")
    else:
        project_dir.mkdir(parents=True)


def seed_starter_code(project_dir: Path, *, overwrite: bool = True) -> dict[Path, bool]:
    """Write starter project helper code into ``code/`` from bundled templates.

    Returns a map from written path to whether the file changed.
    """
    code_dir = project_dir / DEFAULT_PROJECT_CODE_DIR
    result: dict[Path, bool] = {}
    for relative_name, text in iter_starter_code_templates():
        target = code_dir / relative_name
        if target.exists() and not overwrite:
            result[target] = False
            continue
        old = target.read_text(encoding="utf-8") if target.exists() else None
        if old == text:
            result[target] = False
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        result[target] = True
    return result


def seed_research_bootstrap(
    project_dir: Path,
    *,
    project_name: str,
    objective: str,
    venue: str = "EMNLP",
    overwrite: bool = True,
) -> dict[Path, bool]:
    """Write the initial auto-research ledger without claiming readiness.

    The launcher always seeds starter helper code, so daemon empty-directory
    preflight cannot reliably infer that the research ledger is missing. Keep
    this bootstrap deterministic and conservative: it gives the first Engineer
    stable files to extend, while all downstream stages remain non-successful
    until real literature, benchmark, run, and paper artifacts exist.
    """
    files = _research_bootstrap_files(
        project_name=project_name, objective=objective, venue=venue
    )
    result: dict[Path, bool] = {}
    for relative_name, text in files.items():
        target = project_dir / relative_name
        if target.exists() and not overwrite:
            result[target] = False
            continue
        old = target.read_text(encoding="utf-8") if target.exists() else None
        if old == text:
            result[target] = False
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        result[target] = True
    return result


def _research_bootstrap_files(
    *, project_name: str, objective: str, venue: str = "EMNLP"
) -> dict[str, str]:
    from ..skills.venue_profiles import get_venue_profile

    profile = get_venue_profile(venue)
    # Preserve the historical EMNLP brief wording byte-for-byte; only
    # diverge when a non-EMNLP venue is explicitly requested.
    venue_brief_line = (
        "EMNLP/ACL long paper"
        if profile.key == "EMNLP"
        else f"{profile.display_name} two-column paper ({profile.body_page_limit}-page body)"
    )
    pipeline_state = {
        "current_stage": "research",
        "vertical": "research",
        "objective": objective,
        "target_venue": profile.key,
        "paper_scope": "long-paper",
        "stages": {
            "research": {
                "status": "pending",
                "artifact": "research/RESEARCH_BRIEF.md",
                "notes": "Brief + literature combined. Find gap, survey papers, define direction.",
            },
            "plan": {
                "status": "missing",
                "artifact": "research/EXPERIMENT_PLAN.md",
            },
            "benchmark": {
                "status": "missing",
                "artifact": "experiments/BENCHMARK_PROVENANCE.md",
            },
            "run": {"status": "missing"},
            "analysis": {"status": "missing"},
            "draft": {"status": "missing"},
            "review": {"status": "missing"},
            "submission": {"status": "missing"},
        },
        "last_gate": {
            "verdict": "pending",
            "reason": (
                "official launcher seed only; final readiness requires completed "
                "literature grounding, full-scale evidence, paper reviews, and "
                "the L2 reviewer marking `done` against the full pipeline checklist"
            ),
        },
    }
    return {
        "research/PIPELINE_STATE.json": json.dumps(
            pipeline_state,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        "research/RESEARCH_BRIEF.md": (
            "# Research Brief\n\n"
            f"- Project: `{project_name}`\n"
            f"- Research direction (from operator): {objective}\n"
            f"- Target venue: {venue_brief_line}\n"
            "- Current stage: research\n\n"
            "## IMPORTANT: This is a DIRECTION, not a plan\n\n"
            "The operator gave you a research DIRECTION, not a paper plan. "
            "You must:\n\n"
            "1. **Survey the field first.** Search arXiv, Semantic Scholar, "
            "机器之心 for the latest work in this direction. Write "
            "`research/LITERATURE_GROUNDING.json` (≥10 recent papers, ≥3 classics).\n"
            "2. **Read reference code.** Clone top-3 related papers' repos to "
            "`code/references/`. Read their actual code (not just abstracts). "
            "Write `research/CODE_STUDY_NOTES.md` with what you discovered — "
            "limitations, assumptions, missed opportunities.\n"
            "3. **Find YOUR insight.** Based on literature + code study, identify "
            "something surprising, counter-intuitive, or overlooked. Ask yourself:\n"
            "   - What makes this interesting beyond 'we applied X to Y'?\n"
            "   - What is the ONE key insight that makes this work?\n"
            "   - Why hasn't anyone done this before? (If they have, pivot.)\n"
            "4. **Reject mediocre ideas.** Write `research/IDEA_REJECTION_LOG.md`. "
            "You MUST reject at least one candidate (including 'simple reproduction').\n"
            "5. **Then design experiments.** Write `research/EXPERIMENT_PLAN.md` "
            "with your insight as the central thesis, not reproduction.\n\n"
            "## Resources\n\n"
            "- GPU: `~/.argus-skill/capabilities/gpu_resources.json`\n"
            "- API: `~/.argus-skill/capabilities/model_api.json`\n"
            "- Skills: read `argus_builtin_skills/engineer/auto-research-pipeline.md`\n"
        ),
        "research/EXPERIMENT_PLAN.md": (
            "# Experiment Plan\n\n"
            "Seed scaffold only. Do not mark the plan stage ready until "
            ""
            ""
            "and `experiments/BENCHMARK_PROVENANCE.md` contain source-backed content.\n\n"
            "Required method target: use the available GPU budget for a meaningful "
            "domain-appropriate trained/adapted model. Tiny scorers, prompt-only wrappers, "
            "and exact-oracle policies are baselines/smoke tests unless the operator "
            "explicitly lowers the scope.\n\n"
            "Required evidence target: a complete multi-source matrix over at least "
            "3 independent executed real benchmark families for every required "
            "method/baseline condition, drawn from existing real benchmarks or official "
            "task/data releases, with raw rows under `experiments/**` and status/progress "
            "artifacts. Synthetic/local tasks are smoke-only and cannot support final "
            "paper claims.\n"
        ),
        "research/CLAIMS_TO_TEST.md": (
            "# Claims To Test\n\n"
            "Seed scaffold only. Add claims after the literature and benchmark "
            "plan identify the method, baselines, expected effects, ablations, "
            "robustness checks, and failure cases.\n"
        ),
        "research/GO_NO_GO.md": (
            "# Go / No-Go\n\n"
            "Initial decision: no-go for drafting. Advance only after the full "
            "benchmark matrix has completed and the run-stage full-scale evidence "
            "checklist item is satisfied on current experiment artifacts.\n"
        ),
        "experiments/BENCHMARK_PROVENANCE.md": (
            "# Benchmark Provenance\n\n"
            "Seed scaffold only. Record surveyed benchmark papers, repositories, "
            "licenses/access constraints, selected existing real benchmark sources, "
            "sampling/adaptation logic, and the final task schema before running "
            "experiments. Final evidence must not use synthetic/local benchmarks; "
            "synthetic tasks are allowed only as smoke tests and must be excluded from "
            "paper-facing result claims.\n"
        ),
        "experiments/MODEL_SCALE_PLAN.md": (
            "# Model Scale Plan\n\n"
            "Seed scaffold only. Before implementation, record the chosen model/backbone, "
            "parameter count, trainable parameter count, training/adaptation recipe, "
            "dataset size, GPU type/count, memory strategy, expected GPU-hours, checkpoint "
            "or adapter path, and why this is a meaningful frontier-domain model rather "
            "than a toy scorer.\n"
        ),
    }


def iter_starter_code_templates() -> list[tuple[str, str]]:
    """Return deterministic starter-code templates bundled with this package."""
    package_root = resources.files(STARTER_CODE_TEMPLATE_PACKAGE)
    templates: list[tuple[str, str]] = []
    for filename in STARTER_CODE_TEMPLATE_FILES:
        resource = package_root / filename
        templates.append((filename, resource.read_text(encoding="utf-8")))
    return templates


def init_git(project_dir: Path, project_name: str) -> str:
    _run(["git", "init", "--quiet"], cwd=project_dir)
    _run(
        [
            "git",
            "add",
            "AGENTS.md",
            DEFAULT_PROJECT_BUILTIN_SKILLS_DIR,
            DEFAULT_PROJECT_CODE_DIR,
            "research",
            "experiments",
        ],
        cwd=project_dir,
    )
    message = f"Seed {project_name} auto-research workspace\n\n{TRAILER}"
    _run(["git", "commit", "--quiet", "-m", message], cwd=project_dir)
    return _run(["git", "rev-parse", "--short", "HEAD"], cwd=project_dir).strip()


def init_project_venv(project_dir: Path) -> Path:
    """Create a per-project ``.venv`` so the agent can ``pip install`` freely.

    The Argus framework venv (the one running this launcher) must stay clean,
    but the **host system** is treated as a shared ML-ready base layer: any
    package the operator has installed at the system level (typically a
    CUDA-built ``torch`` from the NVIDIA container image, plus tooling like
    ``numpy``) becomes visible inside the project venv via
    ``--system-site-packages``. The agent then ``pip install``s project-
    specific extras (``diffusers``, ``transformers``, ``peft``,
    ``accelerate``, …) into the project venv overlay without polluting the
    framework venv or other projects.

    Why this matters: when the project venv is built without
    ``--system-site-packages`` on a CUDA host, ``import torch`` fails
    inside the project; the agent then either (a) downloads its own
    multi-GB CPU-only torch wheel that ignores the host GPU stack, or
    (b) — worse — produces stub evaluator code that pretends to score
    while reporting ``state: completed``. The system-site-packages
    overlay puts the host's CUDA torch within reach by default, while
    still letting per-project ``pip install`` add overlay packages that
    do not affect other projects.
    """

    venv_dir = project_dir / ".venv"
    if not venv_dir.exists():
        _run(
            [
                str(_ml_base_python()),
                "-m",
                "venv",
                "--upgrade-deps",
                "--system-site-packages",
                str(venv_dir),
            ],
            cwd=project_dir,
            timeout=180,
        )

    # Even on a pre-existing venv, force include-system-site-packages = true
    # so old projects created before this fix also start seeing the host
    # CUDA stack on next daemon round.
    cfg_path = venv_dir / "pyvenv.cfg"
    if cfg_path.exists():
        cfg_lines = []
        saw_flag = False
        for raw in cfg_path.read_text(encoding="utf-8").splitlines():
            if raw.strip().startswith("include-system-site-packages"):
                cfg_lines.append("include-system-site-packages = true")
                saw_flag = True
            else:
                cfg_lines.append(raw)
        if not saw_flag:
            cfg_lines.append("include-system-site-packages = true")
        cfg_path.write_text("\n".join(cfg_lines) + "\n", encoding="utf-8")

    pip_path = venv_dir / "bin" / "pip"
    if not pip_path.exists():
        pip_path = venv_dir / "Scripts" / "pip.exe"  # Windows fallback
    if pip_path.exists():
        try:
            _run(
                [str(pip_path), "install", "--quiet", "requests"],
                cwd=project_dir,
                timeout=180,
            )
        except LaunchError:
            # Network may be flaky; the venv itself is still usable.
            pass

    # Make sure git does not try to track per-project virtualenvs or
    # downloaded model weights / huggingface caches.
    gitignore = project_dir / ".gitignore"
    snippet_pieces = []
    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    if ".venv/" not in existing.split():
        snippet_pieces.append("\n# argus-skill: per-project virtualenv\n.venv/\n")
    if "models/" not in existing.split():
        snippet_pieces.append(
            "\n# argus-skill: per-project model weights / HF cache\n"
            "models/\n"
        )
    if snippet_pieces:
        gitignore.write_text(existing + "".join(snippet_pieces), encoding="utf-8")

    # Pre-create the per-project model directory so HF_HOME et al. point
    # at a real location from round 1. Empty directory is fine; the agent
    # populates it on first download.
    (project_dir / "models").mkdir(exist_ok=True)

    return venv_dir


def start_daemon(project_dir: Path, agents_md: str) -> str:
    objective = _continuous_objective_from_agents(agents_md)
    return _run(
        [
            str(_argus_python()),
            "-m",
            "argus_skill",
            "--daemon",
            "--continuous",
            "--objective",
            objective,
        ],
        cwd=project_dir,
        env=_argus_env(),
        timeout=90,
    )


def status(project_dir: Path) -> str:
    return _run(
        [
            str(_argus_python()),
            "-m",
            "argus_skill",
            "--status",
        ],
        cwd=project_dir,
        env=_argus_env(),
        timeout=30,
    )


def _continuous_objective_from_agents(agents_md: str) -> str:
    for line in agents_md.splitlines():
        if line.startswith("- Primary paper goal: "):
            return line.split(": ", 1)[1]
    return "Start a clean-slate EMNLP/ACL long-paper auto-research project and continue until the L2 reviewer marks `done` against the full pipeline checklist."


def _argus_env() -> dict[str, str]:
    env = os.environ.copy()
    repo_root = Path(__file__).resolve().parents[2]
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = f"{repo_root}{os.pathsep}{existing}" if existing else str(repo_root)
    env.setdefault("ARGUS_SKILL_SOURCE_ROOT", str(repo_root))
    env.setdefault("ARGUS_SKILL_PYTHON", str(_argus_python()))
    return env


def _argus_python() -> Path:
    configured = Path(os.environ.get("ARGUS_SKILL_PYTHON", str(PYTHON))).expanduser()
    if configured.exists():
        return configured
    return Path(sys.executable)


def _interpreter_has_torch(python: Path) -> bool:
    """True when ``python -c 'import torch'`` succeeds for ``python``."""
    try:
        proc = subprocess.run(
            [str(python), "-c", "import torch"],
            capture_output=True,
            timeout=60,
            check=False,
        )
        return proc.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def _ml_base_python() -> Path:
    """Pick the base interpreter for a project venv that can ``import torch``.

    On a CUDA host (e.g. Azure ML PyTorch containers) the GPU-enabled torch
    lives in a conda env exposed via ``$CONDA_PREFIX`` — not in the Argus
    framework venv. Building the project venv on that interpreter with
    ``--system-site-packages`` inherits the host CUDA stack so the agent never
    has to download a multi-GB CPU-only torch wheel (or, worse, fake scoring
    because ``import torch`` failed). Preference order:

    1. ``ARGUS_SKILL_ML_PYTHON`` operator override,
    2. ``$CONDA_PREFIX/bin/python`` (the active conda env),
    3. the Argus framework python (fallback — keeps prior behavior when no
       torch-bearing interpreter is found).
    """
    candidates: list[Path] = []
    override = os.environ.get("ARGUS_SKILL_ML_PYTHON", "").strip()
    if override:
        candidates.append(Path(override).expanduser())
    conda_prefix = os.environ.get("CONDA_PREFIX", "").strip()
    if conda_prefix:
        candidates.append(Path(conda_prefix) / "bin" / "python")
    for cand in candidates:
        if cand.exists() and _interpreter_has_torch(cand):
            return cand
    return _argus_python()


def _run(
    cmd: list[str],
    *,
    cwd: Path,
    env: dict[str, str] | None = None,
    timeout: int = 30,
) -> str:
    proc = subprocess.run(
        cmd,
        cwd=cwd,
        env=env,
        text=True,
        capture_output=True,
        timeout=timeout,
        check=False,
    )
    output = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode != 0:
        rendered = " ".join(cmd)
        raise LaunchError(
            f"command failed with exit {proc.returncode}: {rendered}\n{output.strip()}"
        )
    return output


def _interactive_domain_select() -> str | None:
    """Interactively ask the user to pick a research domain."""
    print("\n🔬 Select a research domain (loads only relevant skills):\n")
    keys = list(AVAILABLE_DOMAINS.keys())
    for i, key in enumerate(keys, 1):
        desc = DOMAIN_DESCRIPTIONS[key]
        print(f"  {i}. {desc}")
    print(f"  {len(keys) + 1}. All domains (load everything — may be slow)")
    print()
    while True:
        try:
            choice = input("Domain [1-{}]: ".format(len(keys) + 1)).strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return None
        if not choice:
            continue
        try:
            idx = int(choice)
        except ValueError:
            # Try matching by name
            if choice.lower() in AVAILABLE_DOMAINS:
                return choice.lower()
            print(f"  Invalid choice. Enter 1-{len(keys) + 1} or a domain name.")
            continue
        if 1 <= idx <= len(keys):
            selected = keys[idx - 1]
            print(f"\n  ✓ Selected: {DOMAIN_DESCRIPTIONS[selected]}\n")
            return selected
        elif idx == len(keys) + 1:
            print("\n  ✓ Loading all domains\n")
            return None
        else:
            print(f"  Invalid choice. Enter 1-{len(keys) + 1}.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="new-auto-research-project",
        description=(
            "Create an agent-emnlp-auto-research-vN workspace from the bundled "
            "AGENTS.md template, export built-in skills, seed starter code, "
            "initialize git, and optionally start the Argus continuous daemon."
        ),
    )
    parser.add_argument(
        "version",
        nargs="?",
        help="version to create, e.g. 15 or v15; omit to pick the next available version",
    )
    parser.add_argument(
        "--parent",
        type=Path,
        default=DEFAULT_PARENT,
        help=f"parent directory for versioned workspaces (default: {DEFAULT_PARENT})",
    )
    parser.add_argument(
        "--project-dir",
        type=Path,
        default=None,
        help="explicit project directory instead of parent + version naming",
    )
    parser.add_argument(
        "--template",
        type=Path,
        default=None,
        help=f"AGENTS template file (default: built-in {DEFAULT_TEMPLATE})",
    )
    parser.add_argument(
        "--objective",
        default=None,
        help="project-specific primary paper goal to place in AGENTS.md and daemon objective",
    )
    parser.add_argument(
        "--non-goals",
        default=None,
        help="project-specific non-goals to place in AGENTS.md",
    )
    parser.add_argument(
        "--compute-budget",
        default=None,
        help="project-specific compute/API budget and stop conditions",
    )
    parser.add_argument(
        "--no-start",
        action="store_true",
        help="create the workspace but do not start the Argus daemon",
    )
    parser.add_argument(
        "--no-git",
        action="store_true",
        help="skip git init/add/commit",
    )
    parser.add_argument(
        "--no-venv",
        action="store_true",
        help=(
            "skip per-project `.venv` bootstrap. By default the launcher "
            "creates an isolated virtualenv at `<project>/.venv` so the "
            "agent can `pip install` experiment dependencies without "
            "polluting the Argus framework venv."
        ),
    )
    parser.add_argument(
        "--venue",
        choices=["emnlp", "aaai"],
        default="emnlp",
        help=(
            "target publication venue (default: emnlp). Selects the format "
            "contract — page budget, mandatory sections, LaTeX style, "
            "anonymity block, and reviewer rubric — written into "
            "research/PIPELINE_STATE.json's `target_venue`."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the resolved project path/version without creating files",
    )
    parser.add_argument(
        "--domain",
        choices=list(AVAILABLE_DOMAINS.keys()),
        default=None,
        help=(
            "research domain to activate (only loads domain-relevant skills). "
            "Available: " + ", ".join(f"{k} ({v})" for k, v in DOMAIN_DESCRIPTIONS.items())
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    # Interactive domain selection if not specified
    domain = args.domain
    if domain is None and sys.stdin.isatty() and not args.dry_run:
        domain = _interactive_domain_select()

    config = LaunchConfig(
        parent=args.parent,
        version=args.version,
        project_dir=args.project_dir,
        template_path=args.template,
        objective=args.objective,
        non_goals=args.non_goals,
        compute_budget=args.compute_budget,
        domain=domain,
        venue=args.venue,
        start_daemon=not args.no_start,
        init_git=not args.no_git,
        dry_run=args.dry_run,
        create_project_venv=not args.no_venv,
    )
    try:
        result = create_project(config)
    except (LaunchError, OSError, subprocess.TimeoutExpired) as exc:
        sys.stderr.write(f"new-auto-research-project: {exc}\n")
        return 2
    print(format_result(result))
    return 0


def format_result(result: LaunchResult) -> str:
    lines = [
        f"project : {result.project_dir}",
        f"version : {result.version}",
        f"domain  : {result.domain or 'all (no filter)'}",
        f"AGENTS  : {result.agents_path}",
        f"skills  : {result.skills_dir}",
        f"code    : {result.project_dir / DEFAULT_PROJECT_CODE_DIR}",
    ]
    if result.dry_run:
        lines.append("dry-run : no files created")
        return "\n".join(lines)
    if result.git_commit:
        lines.append(f"commit  : {result.git_commit}")
    if result.project_venv is not None:
        lines.append(f"venv    : {result.project_venv}")
    lines.append(f"daemon  : {'started' if result.daemon_started else 'not started'}")
    if result.daemon_output.strip():
        lines.append("")
        lines.append(result.daemon_output.strip())
    if result.status_output.strip():
        lines.append("")
        lines.append(result.status_output.strip())
    return "\n".join(lines)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
