"""Project-bootstrap helpers shared by the daemon's continuous-mode seeding.

This module no longer drives a standalone ``argus start`` paper launcher — that
hardcoded paper bypass has been retired. The single supported way to start work
is to run ``argus`` in a project directory and talk to the Manager, which lets
the daemon bootstrap classify the objective's vertical and seed the matching
AGENTS contract (paper vs. optimize).

What remains here are the pure, vertical-agnostic bootstrap primitives the
daemon's ``LifeWorker._seed_project_agents_and_venv`` / ``_seed_bootstrap_task``
call: render an AGENTS.md from a copy-ready template, seed starter helper code,
and build a per-project ``.venv``.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from importlib import resources
from pathlib import Path

from ..skills.builtins import (
    builtin_skill_source_path,
    iter_builtin_skill_texts,
)

DEFAULT_TEMPLATE = "agent-md-new-project-template.md"
DEFAULT_PROJECT_CODE_DIR = "code"
PYTHON = Path(os.environ.get("ARGUS_SKILL_PYTHON", sys.executable))
COPY_READY_HEADING = "## Copy-ready `AGENTS.md`"
HARNESS_DECLARATION_HEADING = "## Argus harness modification map"
HARNESS_ARCHITECTURE_DECLARATION = f"""
{HARNESS_DECLARATION_HEADING}
This workspace is an EMNLP auto-research project generated by the Argus
agent harness. Treat `AGENTS.md`, `research/`, `experiments/`, and `paper/`
as project artifacts. Treat the active `argus_skill` package/source checkout
as the harness that drives the project. Do not mix the two when making fixes.

Runtime route:

```text
argus-skill / python -m argus_skill
  -> argus_skill/apps/cli.py
  -> argus_skill/apps/_runtime.py or argus_skill/daemon/life_worker.py
  -> argus_skill/life/supervisor.py
  -> _SkillLoopRunner.execute(...)
  -> argus_skill/loop.py
  -> argus_skill/engineer/runner.py
  -> argus_skill/reviewer/_core.py
```

Ownership map:

| Concern | Edit here in the Argus source checkout |
| --- | --- |
| CLI flags, REPL, daemon start/stop, status/follow/watch | `argus_skill/apps/cli.py`, `argus_skill/manager/repl.py`, `argus_skill/apps/_runtime.py`, `argus_skill/daemon/life_worker.py`, `argus_skill/apps/_watch.py` |
| One mission's skill matcher -> distiller -> engineer -> reviewer flow | `argus_skill/loop.py` |
| L1 engineer retries, session carryover, watchdogs, backend failures | `argus_skill/engineer/runner.py` |
| L2 reviewer verdicts, JSON schema, reviewer-to-engineer next action | `argus_skill/reviewer/_core.py`, `argus_skill/reviewer/reviewer_schema.json` |
| L4 planner continuous-mode task creation and mission supervision | `argus_skill/life/supervisor.py`, `argus_skill/planner/planner.py` |
| Reviewer-proposed skill memory (selection + validated CRUD, no Manager approval gate), compaction, storage, builtin seeding | `argus_skill/skills/skill_router.py` (SkillRouter: mechanical + independence checks), `argus_skill/manager/skill_review.py` (Manager's post-hoc library PLACEMENT tidy-up only, not a creation gate), `argus_skill/skills/compaction.py`, `argus_skill/skills/store.py`, `argus_skill/skills/builtins.py`, `argus_skill/builtin_skills/` |
| Reviewer-proposed project wiki memory (structured CRUD, no Manager gate), evidence-verbatim anti-fabrication | `argus_skill/wiki/router.py` (WikiRouter), `argus_skill/wiki/store.py`, `argus_skill/wiki/auto_hooks.py`, `argus_skill/skills/provenance.py` |
| EMNLP artifact-validation helpers (importable checks, no completion gating) | `argus_skill/skills/pipeline_contracts.py`, `argus_skill/skills/pipeline_policy.py` |
| Final-submission completion certification (L2 reviewer contract + checklist) | `argus_skill/reviewer/_core.py`, `argus_skill/reviewer/reviewer_schema.json` |
| Academic-language, infrastructure-leak, and visual-layout review tools | `argus_skill/skills/academic_language_review.py`, `argus_skill/skills/paper_infrastructure_review.py`, `argus_skill/skills/paper_layout_review.py` |
| Image-2 paper figure prompt/generation/review/metadata helpers | `argus_skill/tools/image_tool.py` |
| New auto-research project launcher and this declaration | `argus_skill/tools/new_auto_research_project.py` |

Modification rule: final-submission completion is certified by the L2 reviewer
contract — to change what "done" requires, edit the reviewer prompt/checklist in
`argus_skill/reviewer/_core.py` and `reviewer_schema.json`; if an artifact
check should be stricter or looser, change `pipeline_contracts.py`; if an agent
needs different instructions while executing paper work, change the relevant
`argus_skill/builtin_skills/*.md` or `SkillLoop._build_engineer_prompt`. Do not
hand-edit generated review JSON, manifest/freshness records, or
submission-assurance artifacts just to make completion look certified.
""".strip()

STARTER_CODE_TEMPLATE_PACKAGE = "argus_skill.tools.project_templates.code"
STARTER_CODE_TEMPLATE_FILES = (
    "__init__.py",
    "llm.py",
    "gpu_env.py",
    "experiment_io.py",
    "run_experiments.py",
    "generate_image_2.py",
    "generate_image2_figure.py",
)


class LaunchError(RuntimeError):
    """Raised when project bootstrapping cannot safely continue."""


def extract_copy_ready_agents_md(template_text: str) -> str:
    """Return the copy-ready AGENTS.md body from a built-in template.

    The body is wrapped in a fenced block under ``COPY_READY_HEADING`` and may
    itself contain nested code fences (e.g. ```python examples). To avoid
    closing the block at the first nested fence — which silently truncates the
    generated agent prompt — the wrapper uses a longer fence (four backticks)
    and we close only on a fence of at least the opening length with nothing but
    whitespace after it (CommonMark-style). This keeps any inner 3-backtick
    blocks as ordinary body content.
    """
    heading_index = template_text.find(COPY_READY_HEADING)
    if heading_index < 0:
        raise LaunchError(f"template is missing {COPY_READY_HEADING!r}")
    lines = template_text[heading_index:].split("\n")
    open_re = re.compile(r"^[ \t]{0,3}(`{3,})\s*([^`]*)$")
    fence_marker = None
    body_lines: list[str] = []
    open_index = None
    for index, line in enumerate(lines[1:], start=1):
        match = open_re.match(line)
        if match:
            fence_marker = match.group(1)
            open_index = index
            break
    if fence_marker is None or open_index is None:
        raise LaunchError("template is missing the opening markdown fence")
    close_re = re.compile(r"^[ \t]{0,3}`{" + str(len(fence_marker)) + r",}\s*$")
    closed = False
    for line in lines[open_index + 1:]:
        if close_re.match(line):
            closed = True
            break
        body_lines.append(line)
    if not closed:
        raise LaunchError("template is missing the closing markdown fence")
    body = "\n".join(body_lines).strip()
    if not body.startswith("# AGENTS.md"):
        raise LaunchError("copy-ready template body must start with '# AGENTS.md'")
    return body + "\n"


def render_agents_md(
    template_text: str,
    *,
    project_name: str,
    objective: str | None = None,
    non_goals: str | None = None,
    compute_budget: str | None = None,
    append_harness_map: bool = True,
) -> str:
    """Fill the project-specific fields in the copy-ready AGENTS.md template.

    ``append_harness_map`` controls whether the paper-centric Argus harness
    ownership map is appended. It is on by default (the research/paper template
    relies on it) and turned off for optimize-vertical projects, whose AGENTS
    contract is a lean benchmark-optimization mission with no paper pipeline.
    """
    body = extract_copy_ready_agents_md(template_text)
    objective = objective or default_objective(project_name)
    non_goals = non_goals or default_non_goals(project_name)
    compute_budget = compute_budget or default_compute_budget()
    replacements = {
        "[write the target research problem and deliverable]": objective,
        "[write what must not be optimized, copied, or claimed]": non_goals,
        "[write limits and stop conditions]": compute_budget,
        "| [input] | [source] | [status] | [allowed use] | [rationale] |": (
            default_allowed_inputs_table_rows()
        ),
    }
    for old, new in replacements.items():
        body = body.replace(old, new)
    if append_harness_map:
        body = append_harness_architecture_declaration(body)
    unresolved = [
        token
        for token in (
            "[write the target research problem and deliverable]",
            "[write what must not be optimized, copied, or claimed]",
            "[write limits and stop conditions]",
            "| [input] | [source] | [status] | [allowed use] | [rationale] |",
        )
        if token in body
    ]
    if unresolved:
        raise LaunchError(f"rendered AGENTS.md still has placeholders: {unresolved}")
    return body


def append_harness_architecture_declaration(body: str) -> str:
    """Append the Argus harness modification map to generated AGENTS.md."""
    text = body.rstrip()
    if HARNESS_DECLARATION_HEADING in text:
        return text + "\n"
    return f"{text}\n\n{HARNESS_ARCHITECTURE_DECLARATION}\n"


def default_objective(project_name: str) -> str:
    return (
        f"Start {project_name} as a clean-slate EMNLP/ACL long-paper auto-research "
        "workspace: choose an independent frontier-domain thesis from current "
        "research, train or adapt a meaningful domain model with "
        "the available GPU budget, evaluate only on existing real benchmark sources "
        "or official task/data releases, run the full-scale evidence matrix, then write "
        "an exemplar-locked, visually polished EMNLP/ACL long-paper submission package "
        "that the L2 reviewer certifies `done` against the full pipeline checklist."
    )


def default_non_goals(project_name: str) -> str:
    return (
        f"Do not copy, rename, polish, or continue any prior `agent-emnlp-auto-research-v*` "
        f"workspace as {project_name}. Do not reuse prior titles, claims, benchmark "
        "episodes, results, figures, paper generators, review JSON, or paper story unless "
        "listed as allowed raw evidence with license/access status and a narrow rationale."
    )


def _gpu_budget_from_vault() -> str:
    """Render a GPU-allocation clause from the capability vault if available.

    Reads ``~/.argus-skill/capabilities/gpu_resources.json`` via
    :func:`argus_skill.tools.capability_vault.load_gpu_resources` so the
    generated ``AGENTS.md`` automatically reflects the operator's GPU grant
    without forcing the user to retype it on every project.
    """
    try:
        from .capability_vault import load_gpu_resources  # local import to avoid cycle
    except Exception:  # pragma: no cover - defensive
        return ""
    config = load_gpu_resources() or {}
    cuda_vis = str(config.get("cuda_visible_devices") or "").strip()
    if not cuda_vis:
        return ""
    devices = config.get("allowed_devices") or []
    max_mem = config.get("max_gpu_memory_gb")
    parts = [
        f"GPU allocation (from capability vault): ONLY CUDA devices [{cuda_vis}] are available; "
        f"every training/eval/inference command MUST run with CUDA_VISIBLE_DEVICES={cuda_vis} "
        "and MUST NOT touch any other device on the host."
    ]
    if devices:
        parts.append(f"Allowed device indices: {list(devices)}.")
    if max_mem:
        parts.append(f"Aggregate GPU memory budget: ~{max_mem} GB across the allocation.")
    return " ".join(parts)


def _project_venv_clause() -> str:
    """Tell the agent where the project's own virtualenv lives.

    The launcher creates `<project>/.venv` so the agent can pip install
    experiment dependencies without touching the Argus framework venv.
    Without this clause the agent often `pip install`s into whatever
    Python first appears on PATH (which is the Argus venv) and ends up
    polluting the harness with project-specific packages.
    """

    return (
        "Project Python environment: this workspace ships with its own isolated "
        "`./.venv` (created by the launcher). Use `./.venv/bin/python` and "
        "`./.venv/bin/pip` for ALL experiment / dataset / training / inference "
        "code and for any `pip install` of project dependencies. NEVER `pip install` "
        "into the Argus framework Python (the interpreter that runs "
        "`python -m argus_skill.*` / `${ARGUS_SKILL_PYTHON}`) — that interpreter is "
        "reserved exclusively for the argus-skill daemon, reviewer, and helper CLIs. "
        "If a needed package is missing inside `./.venv`, run "
        "`./.venv/bin/pip install <pkg>` from the project root; do not fall back "
        "to system pip or the framework venv."
    )


def default_compute_budget() -> str:
    base = (
        "Use API/model budget only for necessary literature, coding, image-2, review, and "
        "experiment work. Use local GPU capacity for the strongest feasible "
        "domain-appropriate training/adaptation run rather than defaulting to tiny "
        "custom scorers. Stop or ask for operator guidance if a required real benchmark, "
        "model weight/license, GPU capability, or full-scale run is unavailable, or if "
        "repeated repair cycles make no review-relevant progress."
    )
    gpu_clause = _gpu_budget_from_vault()
    venv_clause = _project_venv_clause()
    parts = [p for p in (gpu_clause, venv_clause, base) if p]
    return "\n\n".join(parts)


def default_allowed_inputs_table_rows() -> str:
    return "\n".join(
        [
            "| Operator research playbook | provided by the launcher/operator when available | local operator guidance | Paper-quality and research-process guidance only | Stable cross-project writing and review policy |",
            "| Active Argus package/source checkout | active Python package plus `ARGUS_SKILL_SOURCE_ROOT` when set | local source/package | Reviewer, built-in skills, helper APIs, and daemon runtime | Required toolchain for this workspace without hard-coded host paths |",
            "| Exported built-in skills | `./argus_builtin_skills/*.md`, `./argus_builtin_skills/**/*.md` | generated local copy | Read-only local skill guidance | Keeps the daemon self-contained without copying the whole Argus repository |",
            "| Public literature, datasets, and repositories | verified URLs/scholarly sources | source-specific license/access | Topic discovery, citations, benchmark construction, and baseline implementation | Must be recorded before use in research artifacts |",
        ]
    )


def load_template_text(template_path: Path | None = None) -> str:
    if template_path is not None:
        return template_path.read_text(encoding="utf-8")
    source_path = builtin_skill_source_path() / DEFAULT_TEMPLATE
    if source_path.exists():
        return source_path.read_text(encoding="utf-8")
    for filename, text in iter_builtin_skill_texts():
        if filename == DEFAULT_TEMPLATE:
            return text
    raise LaunchError(f"built-in template not found: {DEFAULT_TEMPLATE}")


def seed_starter_code(project_dir: Path, *, overwrite: bool = True) -> dict[Path, bool]:
    """Write starter project helper code into ``code/`` from bundled templates.

    Returns a map from written path to whether the file changed.
    """
    code_dir = project_dir / DEFAULT_PROJECT_CODE_DIR
    result: dict[Path, bool] = {}
    for relative_name, text in iter_starter_code_templates():
        target = code_dir / relative_name
        if target.exists() and not overwrite:
            result[target] = False
            continue
        old = target.read_text(encoding="utf-8") if target.exists() else None
        if old == text:
            result[target] = False
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        result[target] = True
    return result


def iter_starter_code_templates() -> list[tuple[str, str]]:
    """Return deterministic starter-code templates bundled with this package."""
    package_root = resources.files(STARTER_CODE_TEMPLATE_PACKAGE)
    templates: list[tuple[str, str]] = []
    for filename in STARTER_CODE_TEMPLATE_FILES:
        resource = package_root / filename
        templates.append((filename, resource.read_text(encoding="utf-8")))
    return templates


def init_project_venv(project_dir: Path) -> Path:
    """Create a per-project ``.venv`` so the agent can ``pip install`` freely.

    The Argus framework venv (the one running this launcher) must stay clean,
    but the **host system** is treated as a shared ML-ready base layer: any
    package the operator has installed at the system level (typically a
    CUDA-built ``torch`` from the NVIDIA container image, plus tooling like
    ``numpy``) becomes visible inside the project venv via
    ``--system-site-packages``. The agent then ``pip install``s project-
    specific extras (``diffusers``, ``transformers``, ``peft``,
    ``accelerate``, …) into the project venv overlay without polluting the
    framework venv or other projects.

    Why this matters: when the project venv is built without
    ``--system-site-packages`` on a CUDA host, ``import torch`` fails
    inside the project; the agent then either (a) downloads its own
    multi-GB CPU-only torch wheel that ignores the host GPU stack, or
    (b) — worse — produces stub evaluator code that pretends to score
    while reporting ``state: completed``. The system-site-packages
    overlay puts the host's CUDA torch within reach by default, while
    still letting per-project ``pip install`` add overlay packages that
    do not affect other projects.
    """

    venv_dir = project_dir / ".venv"
    if not venv_dir.exists():
        _run(
            [
                str(_ml_base_python()),
                "-m",
                "venv",
                "--upgrade-deps",
                "--system-site-packages",
                str(venv_dir),
            ],
            cwd=project_dir,
            timeout=180,
        )

    # Even on a pre-existing venv, force include-system-site-packages = true
    # so old projects created before this fix also start seeing the host
    # CUDA stack on next daemon round.
    cfg_path = venv_dir / "pyvenv.cfg"
    if cfg_path.exists():
        cfg_lines = []
        saw_flag = False
        for raw in cfg_path.read_text(encoding="utf-8").splitlines():
            if raw.strip().startswith("include-system-site-packages"):
                cfg_lines.append("include-system-site-packages = true")
                saw_flag = True
            else:
                cfg_lines.append(raw)
        if not saw_flag:
            cfg_lines.append("include-system-site-packages = true")
        cfg_path.write_text("\n".join(cfg_lines) + "\n", encoding="utf-8")

    pip_path = venv_dir / "bin" / "pip"
    if not pip_path.exists():
        pip_path = venv_dir / "Scripts" / "pip.exe"  # Windows fallback
    if pip_path.exists():
        try:
            _run(
                [str(pip_path), "install", "--quiet", "requests"],
                cwd=project_dir,
                timeout=180,
            )
        except LaunchError:
            # Network may be flaky; the venv itself is still usable.
            pass

    # Make sure git does not try to track per-project virtualenvs or
    # downloaded model weights / huggingface caches.
    gitignore = project_dir / ".gitignore"
    snippet_pieces = []
    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    if ".venv/" not in existing.split():
        snippet_pieces.append("\n# argus-skill: per-project virtualenv\n.venv/\n")
    if "models/" not in existing.split():
        snippet_pieces.append(
            "\n# argus-skill: per-project model weights / HF cache\n"
            "models/\n"
        )
    if snippet_pieces:
        gitignore.write_text(existing + "".join(snippet_pieces), encoding="utf-8")

    # Pre-create the per-project model directory so HF_HOME et al. point
    # at a real location from round 1. Empty directory is fine; the agent
    # populates it on first download.
    (project_dir / "models").mkdir(exist_ok=True)

    return venv_dir


def _argus_python() -> Path:
    configured = Path(os.environ.get("ARGUS_SKILL_PYTHON", str(PYTHON))).expanduser()
    if configured.exists():
        return configured
    return Path(sys.executable)


def _interpreter_has_torch(python: Path) -> bool:
    """True when ``python -c 'import torch'`` succeeds for ``python``."""
    try:
        proc = subprocess.run(
            [str(python), "-c", "import torch"],
            capture_output=True,
            timeout=60,
            check=False,
        )
        return proc.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def _ml_base_python() -> Path:
    """Pick the base interpreter for a project venv that can ``import torch``.

    On a CUDA host (e.g. Azure ML PyTorch containers) the GPU-enabled torch
    lives in a conda env exposed via ``$CONDA_PREFIX`` — not in the Argus
    framework venv. Building the project venv on that interpreter with
    ``--system-site-packages`` inherits the host CUDA stack so the agent never
    has to download a multi-GB CPU-only torch wheel (or, worse, fake scoring
    because ``import torch`` failed). Preference order:

    1. ``ARGUS_SKILL_ML_PYTHON`` operator override,
    2. ``$CONDA_PREFIX/bin/python`` (the active conda env),
    3. the Argus framework python (fallback — keeps prior behavior when no
       torch-bearing interpreter is found).
    """
    candidates: list[Path] = []
    override = os.environ.get("ARGUS_SKILL_ML_PYTHON", "").strip()
    if override:
        candidates.append(Path(override).expanduser())
    conda_prefix = os.environ.get("CONDA_PREFIX", "").strip()
    if conda_prefix:
        candidates.append(Path(conda_prefix) / "bin" / "python")
    for cand in candidates:
        if cand.exists() and _interpreter_has_torch(cand):
            return cand
    return _argus_python()


def _run(
    cmd: list[str],
    *,
    cwd: Path,
    env: dict[str, str] | None = None,
    timeout: int = 30,
) -> str:
    proc = subprocess.run(
        cmd,
        cwd=cwd,
        env=env,
        text=True,
        capture_output=True,
        timeout=timeout,
        check=False,
    )
    output = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode != 0:
        rendered = " ".join(cmd)
        raise LaunchError(
            f"command failed with exit {proc.returncode}: {rendered}\n{output.strip()}"
        )
    return output
