"""Backtest adapter scaffold for the quant-factor domain.

The user's real backtest engine and data are assumed to exist but are *external*
to Argus. This module defines the thin contract Argus needs so the agent's
run-stage can drive *some* engine and have every trial captured in the search
ledger — without Argus owning a backtester.

Wire a real engine in by implementing :class:`BacktestEngine` (a ``Protocol``;
no subclassing required) and passing it to :func:`run_backtest`. The wrapper's
only job is **provenance**: it runs the engine and appends the result — success
or failure — to the :class:`~.search_ledger.SearchLedger` at the execution
boundary, so the search breadth is recorded by construction rather than
back-filled by the agent.

This is evidence capture, not a review gate: nothing here decides whether a
factor is good. The L2 reviewer reads the ledger and the report and rules.
"""
from __future__ import annotations

import time
import traceback
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable

from .search_ledger import LedgerRow, SearchLedger


@dataclass(frozen=True)
class BacktestSpec:
    """A single trial to run.

    Carries both *what* to test and the reproducibility context an auditor needs
    to re-run it. ``run_id`` is generated by the caller *before* execution so a
    crashed run still leaves a ledger row referencing it.
    """

    run_id: str
    factor_ids: Sequence[str]
    # "single" | "equal_weight" | "optimized" | ... — how factors are combined.
    weighting: str = "single"
    # Optimization inputs / combination weights, screen params, etc.
    params: Mapping[str, Any] = field(default_factory=dict)
    # Evaluation window label, e.g. "train", "validation", "test", or a
    # walk-forward window id. Drives the oos/is interpretation downstream.
    window: str = ""
    is_out_of_sample: bool = False
    # Reproducibility context (rubber-duck: metrics without this aren't auditable).
    universe: str = ""
    data_snapshot: str = ""
    seed: int | None = None


@dataclass(frozen=True)
class BacktestResult:
    """The outcome of one trial.

    ``metrics`` holds the numbers the analysis stage reads (IC, RankIC, ICIR,
    long-short return, turnover, cost-adjusted return, ...). ``status`` is
    ``"ok"`` on success or ``"error"`` on failure; ``warnings`` surfaces
    partial-failure / data-coverage caveats. ``engine`` identifies the engine
    build so a result can be reproduced.
    """

    run_id: str
    status: str = "ok"
    metrics: Mapping[str, float] = field(default_factory=dict)
    engine: str = ""
    config_hash: str = ""
    warnings: Sequence[str] = field(default_factory=tuple)
    error: str = ""


@runtime_checkable
class BacktestEngine(Protocol):
    """The contract a real backtest engine must satisfy.

    A ``Protocol`` so any object with a matching ``run`` works — no Argus base
    class to inherit. ``name`` identifies the engine build for provenance.
    """

    name: str

    def run(self, spec: BacktestSpec) -> BacktestResult:
        ...


def _result_payload(spec: BacktestSpec, result: BacktestResult) -> dict[str, Any]:
    """Flatten a spec+result into a ledger row payload (audit-complete)."""
    return {
        "run_id": spec.run_id,
        "factor_ids": list(spec.factor_ids),
        "weighting": spec.weighting,
        "params": dict(spec.params),
        "window": spec.window,
        "is_out_of_sample": spec.is_out_of_sample,
        "universe": spec.universe,
        "data_snapshot": spec.data_snapshot,
        "seed": spec.seed,
        "status": result.status,
        "metrics": dict(result.metrics),
        "engine": result.engine,
        "config_hash": result.config_hash,
        "warnings": list(result.warnings),
        "error": result.error,
    }


def run_backtest(
    engine: BacktestEngine, spec: BacktestSpec, ledger: SearchLedger
) -> tuple[BacktestResult, LedgerRow]:
    """Run one trial and record it in the ledger at the execution boundary.

    Returns the engine's result and the ledger row written for it. A raised
    exception from the engine is caught, converted to an ``"error"`` result, and
    *still logged* — so a failed trial cannot silently vanish from the search
    breadth. The exception is not re-raised; callers inspect ``result.status``.
    """
    started = time.time()
    try:
        result = engine.run(spec)
    except Exception as exc:  # noqa: BLE001 - failures must be recorded, not lost
        result = BacktestResult(
            run_id=spec.run_id,
            status="error",
            engine=getattr(engine, "name", ""),
            error=f"{type(exc).__name__}: {exc}",
            warnings=(traceback.format_exc().strip().splitlines()[-1],),
        )
    payload = _result_payload(spec, result)
    payload["elapsed_s"] = round(time.time() - started, 6)
    row = ledger.append(payload)
    return result, row
